<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%title% was replaced by a newer version.' => '',
    '<strong>Confirm</strong> delete file' => '',
    '<strong>Edit</strong> file' => '',
    '<strong>Files</strong> module configuration' => '',
    'Add directory' => '',
    'Adds files module to this space.' => '',
    'Adds files module to your profile.' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'An internal error occurred. Could not load default folder containing all posted files, database not properly initialized.' => '',
    'An internal error occurred. Could not load root folder, database not properly initialized.' => '',
    'Archive %filename% could not be extracted.' => '',
    'Archive (zip) support is not enabled.' => '',
    'Cannot edit non existing file.' => '',
    'Collapse' => '',
    'Could not save file %title%. ' => '',
    'Created at:' => '',
    'Created by:' => '',
    'Creator' => '',
    'Delete' => '',
    'Disable archive (ZIP) support' => '',
    'Do you really want to delete this %number% item(s) with all subcontent?' => '',
    'Edit directory' => '',
    'Edit the file description...' => '',
    'Edit the folder description...' => '',
    'Filesize:' => '',
    'Folder should not start or end with blank space.' => '',
    'Insufficient rights to execute this action.' => '',
    'Invalid parameter.' => '',
    'Last edited at:' => '',
    'Last edited by:' => '',
    'Likes/Comments' => '',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => '',
    'No valid items were selected to move.' => '',
    'Open directory!' => '',
    'Open parent directory!' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Schließen' => '',
    'Selected items...' => '',
    'Show Image' => '',
    'Show Post' => '',
    'Show all files' => '',
    'Show complete file preview' => '',
    'Show on Wall' => '',
    'The archive could not be created.' => '',
    'The folder %filename% already exists. Contents have been overwritten.' => '',
    'The folder with the id %id% does not exist.' => '',
    'This folder is empty.' => '',
    'This folder is still empty.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    ' The folder %filename% could not be saved.' => 'La cartella %filename% non può essere salvata.',
    '%filename% has invalid extension and was skipped.' => 'Il file %filename% ha una estensione non valida e non è stato salvato.',
    '/ (root)' => '/ (root)',
    '<strong>Create</strong> folder' => '<strong>Crea</strong> cartella',
    '<strong>Edit</strong> folder' => '<strong>Modifica</strong> cartella',
    '<strong>Move</strong> files' => '<strong>Sposta</strong> i file',
    'A folder with this name already exists.' => 'Una cartella con lo stesso nome è già esistente',
    'Add file(s)' => 'Aggiungi file',
    'Close' => 'Chiudi',
    'Download' => 'Scarica',
    'Download ZIP' => 'Scarica ZIP',
    'Edit' => 'Modifica',
    'File' => 'File',
    'Files' => 'File',
    'Folder' => 'Cartella',
    'Folder options' => 'Opzioni cartella',
    'Move' => 'Sposta',
    'Name' => 'Nome',
    'Open' => 'Apri',
    'Save' => 'Salva',
    'Size' => 'Dimensione',
    'Updated' => 'Aggiornato',
    'Upload' => 'Carica',
    'Upload ZIP' => 'Carica ZIP',
    'changed:' => 'modificata:',
    'created:' => 'creata:',
];
