<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%title% was replaced by a newer version.' => '',
    '<strong>Confirm</strong> delete file' => '',
    '<strong>Edit</strong> file' => '',
    '<strong>Files</strong> module configuration' => '',
    'Add directory' => '',
    'Adds files module to this space.' => '',
    'Adds files module to your profile.' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'Cannot edit non existing file.' => '',
    'Could not save file %title%. ' => '',
    'Creator' => '',
    'Delete' => '',
    'Disable archive (ZIP) support' => '',
    'Do you really want to delete this %number% item(s) with all subcontent?' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Edit directory' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Insufficient rights to execute this action.' => '',
    'Likes/Comments' => '',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => '',
    'Moving to this folder is invalid.' => '',
    'No valid items were selected to move.' => '',
    'Open file folder' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Root' => '',
    'Selected items...' => '',
    'Show Image' => '',
    'Show Post' => '',
    'Size: {size}' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This folder is empty.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    'ZIP support is not enabled.' => '',
    '/ (root)' => '/ (root)',
    '<strong>Create</strong> folder' => '<strong>Crea</strong> cartella',
    '<strong>Edit</strong> folder' => '<strong>Modifica</strong> cartella',
    '<strong>Move</strong> files' => '<strong>Sposta</strong> i file',
    'A folder with this name already exists.' => 'Una cartella con lo stesso nome è già esistente',
    'Add file(s)' => 'Aggiungi file',
    'Close' => 'Chiudi',
    'Download' => 'Scarica',
    'Download ZIP' => 'Scarica ZIP',
    'Edit' => 'Modifica',
    'File' => 'File',
    'Files' => 'File',
    'Folder' => 'Cartella',
    'Move' => 'Sposta',
    'Name' => 'Nome',
    'Open' => 'Apri',
    'Save' => 'Salva',
    'Size' => 'Dimensione',
    'Updated' => 'Aggiornato',
    'changed:' => 'modificata:',
    'created:' => 'creata:',
];
