<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> delete file' => '',
    '<strong>Edit</strong> file' => '',
    '<strong>File</strong> download url' => '',
    '<strong>File</strong> url' => '',
    '<strong>Files</strong> module configuration' => '',
    '<strong>Folder</strong> url' => '',
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '',
    'A file with that name already exists in this folder.' => '',
    'Add directory' => '',
    'Adds files module to this space.' => '',
    'Adds files module to your profile.' => '',
    'An error occurred while creating folder {folder}.' => '',
    'An error occurred while unpacking {filename}.' => '',
    'Archive %filename% could not be extracted.' => '',
    'Cannot edit non existing file.' => '',
    'Could not find folder with id: %id%' => '',
    'Creator' => '',
    'Delete' => '',
    'Destination folder not found!' => '',
    'Disable archive (ZIP) support' => '',
    'Display Url' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Edit directory' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Folder {name} can\'t be moved to itself!' => '',
    'Folder {name} given folder is not editable!' => '',
    'Import Zip' => '',
    'Likes/Comments' => '',
    'Make Private' => '',
    'Make Public' => '',
    'Moving to the same folder is not valid.' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Replace existing files' => '',
    'Root' => '',
    'Selected items...' => '',
    'Show Post' => '',
    'Size: {size}' => '',
    'Some files could not be imported: ' => '',
    'Some files could not be moved: ' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This file is only visible for you and your friends.' => '',
    'This file is private.' => '',
    'This file is protected.' => '',
    'This file is public.' => '',
    'This folder is empty.' => '',
    'This folder is only visible for you and your friends.' => '',
    'This folder is private.' => '',
    'This folder is protected.' => '',
    'This folder is public.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Upload behaviour for existing file names' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'Use of file indexes for already existing files' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP selected' => '',
    'ZIP support is not enabled.' => '',
    '%filename% has invalid extension and was skipped.' => 'Il file %filename% ha una estensione non valida e non è stato salvato.',
    '/ (root)' => '/ (root)',
    '<strong>Create</strong> folder' => '<strong>Crea</strong> cartella',
    '<strong>Edit</strong> folder' => '<strong>Modifica</strong> cartella',
    '<strong>Move</strong> files' => '<strong>Sposta</strong> i file',
    'A folder with this name already exists.' => 'Una cartella con lo stesso nome è già esistente',
    'Add file(s)' => 'Aggiungi file',
    'Download' => 'Scarica',
    'Download ZIP' => 'Scarica ZIP',
    'Edit' => 'Modifica',
    'File' => 'File',
    'Files' => 'File',
    'Folder' => 'Cartella',
    'Move' => 'Sposta',
    'Name' => 'Nome',
    'Open' => 'Apri',
    'Size' => 'Dimensione',
    'Updated' => 'Aggiornato',
];
