<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> file' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'Cannot edit non existing file.' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Likes/Comments' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Root' => '',
    'Show Image' => '',
    'Size: {size}' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP support is not enabled.' => '',
    '%title% was replaced by a newer version.' => '%title% был заменен на более новую версию.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Подтвердить</strong> удаление файла',
    '<strong>Create</strong> folder' => '<strong>Создать</strong> папку',
    '<strong>Edit</strong> folder' => '<strong>Редактировать</strong> папку',
    '<strong>Files</strong> module configuration' => 'Настройка модуля <strong>Файлы</strong>
',
    '<strong>Move</strong> files' => '<strong>Переместить</strong> файлы',
    'A folder with this name already exists.' => 'Папка с таким именем уже существует.',
    'Add directory' => 'Добавить директорию',
    'Add file(s)' => 'Добавить файл(ы)',
    'Adds files module to this space.' => 'Добавить модуль "Файлы" в это пространство.',
    'Adds files module to your profile.' => 'Добавить модуль "Файлы" в свой профиль.',
    'Close' => 'Закрыть',
    'Could not save file %title%. ' => 'Невозможно сохранить файл %title%.',
    'Creator' => 'Автор',
    'Delete' => 'Удалить',
    'Disable archive (ZIP) support' => 'Отключить поддержка архива (ZIP)',
    'Do you really want to delete this %number% item(s) with all subcontent?' => 'Вы действительно хотите удалить %number% элемент(ов) со всем под-контентом?',
    'Download' => 'Скачать',
    'Download ZIP' => 'Скачать ZIP',
    'Edit' => 'Редактировать',
    'Edit directory' => 'Редактировать директорию',
    'File' => 'Файл',
    'Files' => 'Файлы',
    'Folder' => 'Папка',
    'Insufficient rights to execute this action.' => 'Недостаточно прав для выполнения этого действия.',
    'Move' => 'Переменстить',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Перемещение в ту же папку не является корректным. Выберите корректную родительскую папку для %title%.',
    'Name' => 'Название',
    'No valid items were selected to move.' => 'Нет выбранных элементов для перемещения.',
    'Open' => 'Открыть',
    'Opening archive failed with error code %code%.' => 'Открытие архива потерпело неудачу с ошибкой %code%.',
    'Please select a valid destination folder for %title%.' => 'Пожалуйста, выберите правильную папку назначения для %title%.',
    'Save' => 'Сохранить',
    'Selected items...' => 'Выбранные элементы...',
    'Show Post' => 'Показать сообщение',
    'Size' => 'Размер',
    'This folder is empty.' => 'Эта папка пуста.',
    'Unfortunately you have no permission to upload/edit files.' => 'К сожалению, у Вас нет прав на загрузку / редактирование файлов.',
    'Updated' => 'Обновлено',
    'Upload files or create a subfolder with the buttons on the top.' => 'Загрузите файлы либо создайте под-папку при помощи кнопок выше.',
    'Upload files to the stream to fill this folder.' => 'Загрузите файлы в поток для заполнения этот папки.',
    'ZIP all' => 'ZIP всё',
    'ZIP selected' => 'ZIP выбранное',
    'changed:' => 'изменено:',
    'created:' => 'создано:',
];
