<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> file' => '',
    '<strong>File</strong> download url' => '',
    '<strong>File</strong> url' => '',
    '<strong>Folder</strong> url' => '',
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '',
    'A file with that name already exists in this folder.' => '',
    'An error occurred while creating folder {folder}.' => '',
    'An error occurred while unpacking {filename}.' => '',
    'Cannot edit non existing file.' => '',
    'Could not find folder with id: %id%' => '',
    'Destination folder not found!' => '',
    'Display Url' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Folder {name} can\'t be moved to itself!' => '',
    'Folder {name} given folder is not editable!' => '',
    'Import Zip' => '',
    'Likes/Comments' => '',
    'Make Private' => '',
    'Make Public' => '',
    'Moving to the same folder is not valid.' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Replace existing files' => '',
    'Root' => '',
    'Size: {size}' => '',
    'Some files could not be imported: ' => '',
    'Some files could not be moved: ' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This file is only visible for you and your friends.' => '',
    'This file is private.' => '',
    'This file is protected.' => '',
    'This file is public.' => '',
    'This folder is only visible for you and your friends.' => '',
    'This folder is private.' => '',
    'This folder is protected.' => '',
    'This folder is public.' => '',
    'Upload behaviour for existing file names' => '',
    'Use of file indexes for already existing files' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP support is not enabled.' => '',
    '%filename% has invalid extension and was skipped.' => '%filename% имеет недопустимое расширение и был пропущен.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Подтвердить</strong> удаление файла',
    '<strong>Create</strong> folder' => '<strong>Создать</strong> папку',
    '<strong>Edit</strong> folder' => '<strong>Редактировать</strong> папку',
    '<strong>Files</strong> module configuration' => 'Настройка модуля <strong>Файлы</strong>
',
    '<strong>Move</strong> files' => '<strong>Переместить</strong> файлы',
    'A folder with this name already exists.' => 'Папка с таким именем уже существует.',
    'Add directory' => 'Добавить директорию',
    'Add file(s)' => 'Добавить файл(ы)',
    'Adds files module to this space.' => 'Добавить модуль "Файлы" в это пространство.',
    'Adds files module to your profile.' => 'Добавить модуль "Файлы" в свой профиль.',
    'Archive %filename% could not be extracted.' => 'Архив %filename% не может быть извлечён.',
    'Creator' => 'Автор',
    'Delete' => 'Удалить',
    'Disable archive (ZIP) support' => 'Отключить поддержка архива (ZIP)',
    'Download' => 'Скачать',
    'Download ZIP' => 'Скачать ZIP',
    'Edit' => 'Редактировать',
    'Edit directory' => 'Редактировать директорию',
    'File' => 'Файл',
    'Files' => 'Файлы',
    'Folder' => 'Папка',
    'Move' => 'Переменстить',
    'Name' => 'Название',
    'Open' => 'Открыть',
    'Opening archive failed with error code %code%.' => 'Открытие архива потерпело неудачу с ошибкой %code%.',
    'Please select a valid destination folder for %title%.' => 'Пожалуйста, выберите правильную папку назначения для %title%.',
    'Selected items...' => 'Выбранные элементы...',
    'Show Post' => 'Показать сообщение',
    'Size' => 'Размер',
    'This folder is empty.' => 'Эта папка пуста.',
    'Unfortunately you have no permission to upload/edit files.' => 'К сожалению, у Вас нет прав на загрузку / редактирование файлов.',
    'Updated' => 'Обновлено',
    'Upload files or create a subfolder with the buttons on the top.' => 'Загрузите файлы либо создайте под-папку при помощи кнопок выше.',
    'Upload files to the stream to fill this folder.' => 'Загрузите файлы в поток для заполнения этот папки.',
    'ZIP selected' => 'ZIP выбранное',
];
