<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%filename% has invalid extension and was skipped.' => 'archivo %filename% tiene una extensión inválida y fue omitido.',
    '/ (root)' => '/ (raíz)',
    '<strong>Confirm</strong> delete file' => '<strong>Confirme</strong> eliminación del archivo',
    '<strong>Create</strong> folder' => '<strong>Crear</strong> carpeta',
    '<strong>Edit</strong> file' => '<strong>Editar</strong> archivo',
    '<strong>Edit</strong> folder' => '<strong>Edit</strong> carpeta',
    '<strong>File</strong> download url' => 'Url de descarga del <strong>Archivo</strong>',
    '<strong>File</strong> url' => 'Url del <strong>Archivo</strong>',
    '<strong>Files</strong> module configuration' => 'Configuración del módulo <strong>Archivos</strong>',
    '<strong>Folder</strong> url' => 'Url de la <strong>Carpeta</strong>',
    '<strong>Move</strong> files' => '<strong>Mover</strong> archivos',
    'A file with that name already exists in this folder.' => 'Ya existe un archivo con este nombre en la carpeta.',
    'A folder with this name already exists.' => 'Ya existe una carpeta con este nombre.',
    'Add directory' => 'Agregar directorio',
    'Add file(s)' => 'Agregar archivo(s)',
    'Adds files module to this space.' => 'Añade el módulo de archivos a este espacio',
    'Adds files module to your profile.' => 'Añade el módulo de archivos a tu perfil',
    'An error occurred while creating folder {folder}.' => 'Ocurrió un error mientras se creaba la carpeta {folder}.',
    'An error occurred while unpacking {filename}.' => 'Ocurrió un error mientras se desempaquetaba {filename}.',
    'Archive %filename% could not be extracted.' => 'El archivo %filename% no pudo ser extraído.',
    'Cannot edit non existing file.' => 'No se puede editar un archivo que no existe.',
    'Could not find folder with id: %id%' => 'No se pudo encontrar una carpeta con id: %id%',
    'Creator' => 'Creador',
    'Delete' => 'Eliminar',
    'Destination folder not found!' => '¡No se encontró la carpeta de destino!',
    'Disable archive (ZIP) support' => 'Deshabilitar soporte para archivos ZIP',
    'Display Url' => 'Mostrar Url',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '¿Realmente quieres eliminar {number} ítem(es) y todo su subcontenido?',
    'Download' => 'Descargar',
    'Download ZIP' => 'Descargar como ZIP',
    'Edit' => 'Editar',
    'Edit directory' => 'Editar directorio',
    'File' => 'Archivo',
    'Files' => 'Archivos',
    'Files from the stream' => 'Archivos de la línea de tiempo',
    'Folder' => 'Carpeta',
    'Folder should not start or end with blank space.' => 'El nombre de la carpeta no debería comenzar ni terminar con espacios en blanco.',
    'Folder {name} can\'t be moved to itself!' => '¡Carpeta {name} no se puede mover a su mismo lugar!',
    'Folder {name} given folder is not editable!' => '¡Carpeta {name} no es editable!',
    'Insufficient rights to execute this action.' => 'Permisos insuficientes para ejecutar esta acción.',
    'Import Zip' => 'Importar archivo ZIP',
    'Likes/Comments' => 'Me gusta/Comentarios',
    'Make Private' => 'Hacerlo Privado',
    'Make Public' => 'Hacerlo Público',
    'Move' => 'Mover',
    'Moving to the same folder is not valid.' => 'No es válido mover a la misma carpeta.',
    'Moving to this folder is invalid.' => 'Mover a esta carpeta es inválido.',
    'Name' => 'Nombre',
    'Open' => 'Abrir',
    'Open file folder' => 'Abrir carpeta de archivos',
    'Opening archive failed with error code %code%.' => 'La apertura del archivo falló con código de error %code%.',
    'Please select a valid destination folder for %title%.' => 'Por favor, seleccione un destino válido para la carpeta no título %title%.',
    'Replace existing files' => 'Reemplazar los actuales',
    'Root' => 'Raíz',
    'Selected items...' => 'Ítemes seleccionados...',
    'Show Post' => 'Mostrar la publicación',
    'Size' => 'Tamaño',
    'Size: {size}' => 'Tamaño: {size}',
    'Some files could not be imported: ' => 'Algunos archivos no pudieron ser importados: ',
    'Some files could not be moved: ' => 'Algunos archivos no pudieron ser movidos: ',
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '<strong>Nota:</strong> El comportamiento de reemplazo no es soportado al importar archivos zip',
    'The root folder is the entry point that contains all available files.' => '',
    'This file is private.' => 'Este archivo es privado',
    'This file is public.' => 'Este archivo es público',
    'This folder is empty.' => 'Esta carpeta está vacía.',
    'This folder is private.' => 'Esta carpeta es privada.',
    'This folder is public.' => 'Esta carpeta es pública.',
    'Unfortunately you have no permission to upload/edit files.' => 'No tienes permiso para subir o editar archivos.',
    'Updated' => 'Actualizado el',
    'Upload behaviour for existing file names' => 'Comportamiento de subida para los índices de los nombres de archivos existentes',
    'Upload files or create a subfolder with the buttons on the top.' => 'Sube archivos o crea una subcarpeta usando los botones de más arriba.',
    'Upload files to the stream to fill this folder.' => 'Sube archivos a la línea de tiempo para llenar la carpeta.',
    'Use of file indexes for already existing files' => 'Usar los archivos índices actuales',
    'You can find all files that have been posted to this stream here.' => 'Aquí puedes encontrar todos los archivos que han sido publicados en esta línea de tiempo',
    'ZIP selected' => 'Descargar como ZIP',
    'ZIP support is not enabled.' => 'Soporte para archivos ZIP no está habilitado.',
];
