<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%title% was replaced by a newer version.' => '',
    '<strong>Edit</strong> file' => '',
    '<strong>Files</strong> module configuration' => '',
    'A folder with this name already exists.' => '',
    'Adds files module to this space.' => '',
    'Adds files module to your profile.' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'Cannot edit non existing file.' => '',
    'Could not save file %title%. ' => '',
    'Disable archive (ZIP) support' => '',
    'Do you really want to delete this %number% item(s) with all subcontent?' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Insufficient rights to execute this action.' => '',
    'Likes/Comments' => '',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => '',
    'Moving to this folder is invalid.' => '',
    'No valid items were selected to move.' => '',
    'Open file folder' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Root' => '',
    'Selected items...' => '',
    'Show Image' => '',
    'Size: {size}' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This folder is empty.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    'ZIP support is not enabled.' => '',
    'changed:' => '',
    'created:' => '',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Dosya</strong> silmeyi onayla',
    '<strong>Create</strong> folder' => '<strong>Klasör</strong> oluştur',
    '<strong>Edit</strong> folder' => '<strong>Klasör</strong> düzenle',
    '<strong>Move</strong> files' => '<strong>Klasörü</strong> taşı',
    'Add directory' => 'Dizin ekle',
    'Add file(s)' => 'Dosya Ekle',
    'Close' => 'Kapat',
    'Creator' => 'Yaratıcı',
    'Delete' => 'Sil',
    'Download' => 'İndir',
    'Download ZIP' => 'ZİP İndir',
    'Edit' => 'Düzenle',
    'Edit directory' => 'Düzenleme dizini',
    'File' => 'Dosya',
    'Files' => 'Dosyalar',
    'Folder' => 'Klasör',
    'Move' => 'Taşı',
    'Name' => 'Ad',
    'Open' => 'Aç',
    'Save' => 'Kaydet',
    'Show Post' => 'Gönderiyi göster',
    'Size' => 'Boyut',
    'Updated' => 'Güncel',
];
