<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%filename% has invalid extension and was skipped.' => '',
    '%title% was replaced by a newer version.' => '',
    '<strong>Edit</strong> file' => '',
    '<strong>Files</strong> module configuration' => '',
    'A folder with this name already exists.' => '',
    'Adds files module to this space.' => '',
    'Adds files module to your profile.' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'An internal error occurred. Could not load default folder containing all posted files, database not properly initialized.' => '',
    'An internal error occurred. Could not load root folder, database not properly initialized.' => '',
    'Archive %filename% could not be extracted.' => '',
    'Archive (zip) support is not enabled.' => '',
    'Cannot edit non existing file.' => '',
    'Collapse' => '',
    'Could not save file %title%. ' => '',
    'Created at:' => '',
    'Created by:' => '',
    'Disable archive (ZIP) support' => '',
    'Do you really want to delete this %number% item(s) with all subcontent?' => '',
    'Edit the file description...' => '',
    'Edit the folder description...' => '',
    'Filesize:' => '',
    'Folder options' => '',
    'Folder should not start or end with blank space.' => '',
    'Insufficient rights to execute this action.' => '',
    'Invalid parameter.' => '',
    'Last edited at:' => '',
    'Last edited by:' => '',
    'Likes/Comments' => '',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => '',
    'No valid items were selected to move.' => '',
    'Open directory!' => '',
    'Open parent directory!' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Schließen' => '',
    'Selected items...' => '',
    'Show Image' => '',
    'Show all files' => '',
    'Show complete file preview' => '',
    'Show on Wall' => '',
    'The archive could not be created.' => '',
    'The folder %filename% already exists. Contents have been overwritten.' => '',
    'The folder with the id %id% does not exist.' => '',
    'This folder is empty.' => '',
    'This folder is still empty.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    'changed:' => '',
    'created:' => '',
    ' The folder %filename% could not be saved.' => '%filename% klasörü kaydedilemedi.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Dosya</strong> silmeyi onayla',
    '<strong>Create</strong> folder' => '<strong>Klasör</strong> oluştur',
    '<strong>Edit</strong> folder' => '<strong>Klasör</strong> düzenle',
    '<strong>Move</strong> files' => '<strong>Klasörü</strong> taşı',
    'Add directory' => 'Dizin ekle',
    'Add file(s)' => 'Dosya Ekle',
    'Close' => 'Kapat',
    'Creator' => 'Yaratıcı',
    'Delete' => 'Sil',
    'Download' => 'İndir',
    'Download ZIP' => 'ZİP İndir',
    'Edit' => 'Düzenle',
    'Edit directory' => 'Düzenleme dizini',
    'File' => 'Dosya',
    'Files' => 'Dosyalar',
    'Folder' => 'Klasör',
    'Move' => 'Taşı',
    'Name' => 'Ad',
    'Open' => 'Aç',
    'Save' => 'Kaydet',
    'Show Post' => 'Gönderiyi göster',
    'Size' => 'Boyut',
    'Updated' => 'Güncel',
    'Upload' => 'Yükle',
    'Upload ZIP' => 'ZİP Yükle',
];
