<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' The folder %filename% could not be saved.' => ' Le dossier %filename% n\'a pu être enregistré.',
    '%filename% has invalid extension and was skipped.' => '%filename% n\'a pas une extension valide et a été ignoré.',
    '%title% was replaced by a newer version.' => '%title% a été remplacé par une nouvelle version.',
    '/ (root)' => '/ (racine)',
    '<strong>Confirm</strong> delete file' => '<strong>Confirmer</strong> la suppression du fichier',
    '<strong>Create</strong> folder' => '<strong>Créer</strong> un dossier',
    '<strong>Edit</strong> folder' => '<strong>Modifier</strong> le dossier',
    '<strong>Move</strong> files' => '<strong>Déplacer</strong> les fichiers',
    'A folder with this name already exists' => 'Un dossier portant ce nom existe déjà',
    'Add directory' => 'Ajouter un répertoire',
    'Add file(s)' => 'Ajouter des fichiers',
    'Adds an file module to this space.' => 'Ajoute un module fichier à cet espace.',
    'Adds files module to your profile.' => 'Ajoute le module fichiers à votre profil.',
    'All posted files' => 'Tous les fichiers chargés',
    'Archive' => 'Archive',
    'Archive %filename% could not be extracted.' => 'L\'archive %filename% n\'a pas pu être extraite.',
    'Archive folder' => 'Dossier de l\'archive',
    'Archive selected' => 'Archive sélectionnée',
    'Close' => 'Fermer',
    'Could not save file %title%. ' => 'Impossible d\'enregistrer le fichier %title%. ',
    'Creator' => 'Créateur',
    'Delete' => 'Supprimer',
    'Do you really want to delete this %number% item(s) wit all subcontent?' => 'Voulez-vous vraiment supprimer cet(ces) %number% élément(s) avec tout leur contenu ?',
    'Download' => 'Télécharger',
    'Download .zip' => 'Télécharger .zip',
    'Download zip' => 'Télécharger zip',
    'Edit' => 'Modifier',
    'Edit directory' => 'Modifier le répertoire',
    'Enable Zip Support' => 'Activer le support Zip',
    'File' => 'Fichier',
    'Files' => 'Fichiers',
    'Files Module Configuration' => 'Configuration du Module Fichiers',
    'Folder' => 'Dossier',
    'Folder options' => 'Options des dossiers',
    'Insufficient rights to execute this action.' => 'Droits insuffisants pour effectuer cette action.',
    'Invalid parameter.' => 'Paramètre invalide',
    'Move' => 'Déplacer',
    'Move file' => 'Déplacer le fichier',
    'Move folder' => 'Déplacer le dossier',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Le déplacement vers le même dossier n\'est pas possible. Choisir un dossier de destination pour %title%.',
    'Name' => 'Nom',
    'No valid items were selected to move.' => 'Aucun élément valide n\'a été sélectionné pour le déplacement.',
    'Open' => 'Ouvrir',
    'Opening archive failed with error code %code%.' => 'L\'ouverture de l\'archive a échoué avec le code erreur %code%.',
    'Please select a valid destination folder for %title%.' => 'Merci de choisir un dossier de destination valide pour %title%.',
    'Save' => 'Enregistrer',
    'Selected items...' => 'Elément(s) sélectionné(s)...',
    'Should not start or end with blank space.' => 'Ne doit pas commencer ou terminer par un espace.',
    'Show' => 'Montrer',
    'Show Image' => 'Montrer l\'image',
    'Show Post' => 'Montrer le contenu',
    'Size' => 'Taille',
    'The archive could not be created.' => 'L\'archive n\'a pas pu être créée.',
    'The folder %filename% already exists. Contents have been overwritten.' => 'Le dossier %filename% existe déjà. Les contenus ont été écrasés.',
    'The folder with the id %id% does not exist.' => 'Le dossier avec l\'id %id% n\'existe pas.',
    'This folder is empty.' => 'Ce dossier est vide.',
    'Unfortunately you have no permission to upload/edit files.' => 'Malheureusement, vous n\'avez pas la permission pour ajouter/modifier des fichiers.',
    'Updated' => 'Mis à jour',
    'Upload' => 'Ajouter',
    'Upload .zip' => 'Ajouter .zip',
    'Upload files or create a subfolder with the buttons on the top.' => 'Ajouter des fichiers ou créer un sous-dossier avec les boutons du dessus.',
    'Upload files to the stream to fill this folder.' => 'Ajouter des fichiers au flux pour remplir ce dossier.',
    'Zip support is not enabled.' => 'Le support du Zip n\'est pas activé.',
    'root' => 'racine',
];
