<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' The folder %filename% could not be saved.' => '',
    '%filename% has invalid extension and was skipped.' => '',
    '%title% was replaced by a newer version.' => '',
    '/ (root)' => '',
    '<strong>Add file(s)</strong>' => '',
    '<strong>Create</strong> folder' => '',
    '<strong>Edit</strong> folder' => '',
    '<strong>Move</strong> files' => '',
    'A folder with this name already exists' => '',
    'Add directory' => '',
    'All posted files' => '',
    'Archive %filename% could not be extracted.' => '',
    'Close' => '',
    'Could not save file %title%. ' => '',
    'Creator' => '',
    'Delete' => '',
    'Download' => '',
    'Download .zip' => '',
    'Download zip' => '',
    'Edit' => '',
    'Edit directory' => '',
    'Files' => '',
    'Move' => '',
    'Move file' => '',
    'Move folder' => '',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => '',
    'Name' => '',
    'No files found.' => '',
    'No valid items were selected to move.' => '',
    'Open' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Save' => '',
    'Should not start or end with blank space.' => '',
    'Show' => '',
    'Show Image' => '',
    'Show Post' => '',
    'Size' => '',
    'The archive could not be created.' => '',
    'The folder %filename% already exists. Contents have been overwritten.' => '',
    'The folder with the id %id% does not exist.' => '',
    'Updated' => '',
    'Upload .zip' => '',
    'root' => '',
];
