<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Root' => '',
    'Size: {size}' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP support is not enabled.' => '',
    '%title% was replaced by a newer version.' => '%title% a été remplacé par une nouvelle version.',
    '/ (root)' => '/ (racine)',
    '<strong>Confirm</strong> delete file' => '<strong>Confirmer</strong> la suppression du fichier',
    '<strong>Create</strong> folder' => '<strong>Créer</strong> un dossier',
    '<strong>Edit</strong> file' => '<strong>Modifier</strong> le fichier',
    '<strong>Edit</strong> folder' => '<strong>Modifier</strong> le dossier',
    '<strong>Files</strong> module configuration' => '<strong>Configuration</strong> du module fichier',
    '<strong>Move</strong> files' => '<strong>Déplacer</strong> les fichiers',
    'A folder with this name already exists.' => 'Un dossier portant ce nom existe déjà',
    'Add directory' => 'Ajouter un répertoire',
    'Add file(s)' => 'Ajouter des fichiers',
    'Adds files module to this space.' => 'Ajoute le module fichier à cet espace.',
    'Adds files module to your profile.' => 'Ajoute le module fichiers à votre profil.',
    'An internal error occurred. Could not find folder with id: %id%' => 'Une erreur interne s\'est produite. Impossible de trouver le dossier avec l\'id : %id%',
    'Cannot edit non existing file.' => 'Impossible de modifier un fichier qui n\'existe pas.',
    'Close' => 'Fermer',
    'Could not save file %title%. ' => 'Impossible d\'enregistrer le fichier %title%. ',
    'Creator' => 'Créateur',
    'Delete' => 'Supprimer',
    'Disable archive (ZIP) support' => 'Désactiver le support d\'archive (zip)',
    'Do you really want to delete this %number% item(s) with all subcontent?' => 'Voulez-vous vraiment supprimer cet(ces) %number% élément(s) avec tout leur contenu ?',
    'Download' => 'Télécharger',
    'Download ZIP' => 'Télécharger zip',
    'Edit' => 'Modifier',
    'Edit directory' => 'Modifier le répertoire',
    'File' => 'Fichier',
    'Files' => 'Fichiers',
    'Folder' => 'Dossier',
    'Folder should not start or end with blank space.' => 'Le nom du dossier ne doit pas commencer ou se terminer par un espace.',
    'Insufficient rights to execute this action.' => 'Droits insuffisants pour effectuer cette action.',
    'Likes/Comments' => 'Aime/Commentaires',
    'Move' => 'Déplacer',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Le déplacement vers le même dossier n\'est pas possible. Choisir un dossier de destination pour %title%.',
    'Name' => 'Nom',
    'No valid items were selected to move.' => 'Aucun élément valide n\'a été sélectionné pour le déplacement.',
    'Open' => 'Ouvrir',
    'Opening archive failed with error code %code%.' => 'L\'ouverture de l\'archive a échoué avec le code erreur %code%.',
    'Please select a valid destination folder for %title%.' => 'Merci de choisir un dossier de destination valide pour %title%.',
    'Save' => 'Enregistrer',
    'Selected items...' => 'Elément(s) sélectionné(s)...',
    'Show Image' => 'Montrer l\'image',
    'Show Post' => 'Montrer le contenu',
    'Size' => 'Taille',
    'This folder is empty.' => 'Ce dossier est vide.',
    'Unfortunately you have no permission to upload/edit files.' => 'Malheureusement, vous n\'avez pas la permission pour ajouter/modifier des fichiers.',
    'Updated' => 'Mis à jour',
    'Upload files or create a subfolder with the buttons on the top.' => 'Ajouter des fichiers ou créer un sous-dossier avec les boutons du dessus.',
    'Upload files to the stream to fill this folder.' => 'Ajouter des fichiers au flux pour remplir ce dossier.',
    'ZIP all' => 'Tout zipper',
    'ZIP selected' => 'Zip sélectionné',
    'changed:' => 'Modifié :',
    'created:' => 'Créé :',
];
