<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '',
    'Import Zip' => '',
    'Replace existing files' => '',
    'This file is only visible for you and your friends.' => '',
    'This file is protected.' => '',
    'This folder is only visible for you and your friends.' => '',
    'This folder is protected.' => '',
    'Upload behaviour for existing file names' => '',
    'Use of file indexes for already existing files' => '',
    '%filename% has invalid extension and was skipped.' => '%filename% possui extensão inválida e foi ignorado.',
    '/ (root)' => '/ (raiz)',
    '<strong>Confirm</strong> delete file' => '<strong>Confirmar</strong> exclusão de arquivo',
    '<strong>Create</strong> folder' => '<strong>Criar</strong> pasta',
    '<strong>Edit</strong> file' => '<strong>Alterar</strong> arquivo',
    '<strong>Edit</strong> folder' => '<strong>Alterar</strong> pasta',
    '<strong>File</strong> download url' => 'Endereço de download do <strong>arquivo</strong>',
    '<strong>File</strong> url' => 'Endereço do <strong>arquivo</strong>',
    '<strong>Files</strong> module configuration' => 'Configuração do módulo de <strong>Arquivos</strong>',
    '<strong>Folder</strong> url' => 'Endereço da <strong>pasta</strong>',
    '<strong>Move</strong> files' => '<strong>Mover</strong> arquivos',
    'A file with that name already exists in this folder.' => 'Um arquivo com esse nome já existe nessa pasta.',
    'A folder with this name already exists.' => 'Já existe uma pasta com esse nome.',
    'Add directory' => 'Adicionar pasta',
    'Add file(s)' => 'Adicionar arquivo(s)',
    'Adds files module to this space.' => 'Adicionar o módulo de arquivos neste espaço.',
    'Adds files module to your profile.' => 'Adicionar o módulo de arquivos no seu perfil.',
    'An error occurred while creating folder {folder}.' => 'Um erro ocorreu na criação da pasta {folder}.',
    'An error occurred while unpacking {filename}.' => 'Um erro ocorreu ao descompactar {filename}',
    'Archive %filename% could not be extracted.' => 'Arquivo %filename% não pôde ser extraído.',
    'Cannot edit non existing file.' => 'Não é possível editar um arquivo inexistente.',
    'Could not find folder with id: %id%' => 'Não foi possível achar a pasta com o id: %id%',
    'Creator' => 'Criador',
    'Delete' => 'Apagar',
    'Destination folder not found!' => 'Pasta de destino não encontrada!',
    'Disable archive (ZIP) support' => 'Desabilitar suporte a arquivos ZIP',
    'Display Url' => 'Exibir endereço',
    'Do you really want to delete this {number} item(s) with all subcontent?' => 'Você realmente quer apagar {number} item(ns) com todos os seus conteúdos?',
    'Download' => 'Baixar',
    'Download ZIP' => 'Baixar ZIP',
    'Edit' => 'Alterar',
    'Edit directory' => 'Alterar pasta',
    'File' => 'Arquivo',
    'Files' => 'Arquivos',
    'Files from the stream' => 'Arquivos do mural',
    'Folder' => 'Pasta',
    'Folder should not start or end with blank space.' => 'Nome de pasta não pode iniciar ou terminar com espaço em branco.',
    'Folder {name} can\'t be moved to itself!' => 'Não é possível mover a pasta {name} para dentro dela mesma!',
    'Folder {name} given folder is not editable!' => 'A pasta {name} não é editável!',
    'Likes/Comments' => 'Curtidas/Comentários',
    'Make Private' => 'Tornar privado',
    'Make Public' => 'Tornar público',
    'Move' => 'Mover',
    'Moving to the same folder is not valid.' => 'Não é possível mover para a mesma pasta.',
    'Moving to this folder is invalid.' => 'Não é possível mover para essa pasta.',
    'Name' => 'Nome',
    'Open' => 'Abrir',
    'Open file folder' => 'Abrir essa pasta',
    'Opening archive failed with error code %code%.' => 'Erro ao abrir o arquivo. Código: %code%',
    'Please select a valid destination folder for %title%.' => 'Por favor, selecione uma pasta de destino válida para %title%.',
    'Root' => 'Raiz',
    'Selected items...' => 'Itens selecionados...',
    'Show Post' => 'Exibir Publicação',
    'Size' => 'Tamanho',
    'Size: {size}' => 'Tamanho: {size}',
    'Some files could not be imported: ' => 'Alguns arquivos não puderam ser importados:',
    'Some files could not be moved: ' => 'Alguns arquivos não puderam ser movidos:',
    'The root folder is the entry point that contains all available files.' => 'A pasta raiz é o ponto de entrada que contém todos os arquivos disponíveis.',
    'This file is private.' => 'Esse arquivo é privado.',
    'This file is public.' => 'Esse arquivo é público.',
    'This folder is empty.' => 'Essa pasta está vazia.',
    'This folder is private.' => 'Essa pasta é privada.',
    'This folder is public.' => 'Essa pasta é pública.',
    'Unfortunately you have no permission to upload/edit files.' => 'Infelizmente, você não tem permissão para transferir/alterar arquivos.',
    'Updated' => 'Atualizado',
    'Upload files or create a subfolder with the buttons on the top.' => 'Transfira arquivos ou crie uma subpasta usando os botões na parte superior.',
    'Upload files to the stream to fill this folder.' => 'Transfira arquivos para o mural para preencher esta pasta.',
    'You can find all files that have been posted to this stream here.' => 'Você pode encontrar todos os arquivos enviados para esse mural aqui.',
    'ZIP selected' => 'ZIP selecionado',
    'ZIP support is not enabled.' => 'Suporte para arquivos ZIP não habilitado.',
];
