<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> file' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'An internal error occurred. Could not load default folder containing all posted files, database not properly initialized.' => '',
    'An internal error occurred. Could not load root folder, database not properly initialized.' => '',
    'Cannot edit non existing file.' => '',
    'Collapse' => '',
    'Created at:' => '',
    'Created by:' => '',
    'Edit the file description...' => '',
    'Edit the folder description...' => '',
    'Filesize:' => '',
    'Last edited at:' => '',
    'Last edited by:' => '',
    'Likes/Comments' => '',
    'Open directory!' => '',
    'Open parent directory!' => '',
    'Schließen' => '',
    'Show Image' => '',
    'Show all files' => '',
    'Show complete file preview' => '',
    'Show on Wall' => '',
    'This folder is still empty.' => '',
    ' The folder %filename% could not be saved.' => 'A pasta %filename% não pôde ser salva.',
    '%filename% has invalid extension and was skipped.' => '%filename% possui extensão inválida e foi ignorada.',
    '%title% was replaced by a newer version.' => '%title% foi substituído por uma nova versão.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Confirme</strong> excluir arquivo',
    '<strong>Create</strong> folder' => '<strong>Criar</strong> pasta',
    '<strong>Edit</strong> folder' => '<strong>Editar</strong> pasta',
    '<strong>Files</strong> module configuration' => 'Configuração do módulo de <strong>Arquivos</strong>',
    '<strong>Move</strong> files' => '<strong>Mover</strong> arquivos',
    'A folder with this name already exists.' => 'Já existe uma pasta com esse nome.',
    'Add directory' => 'Adicionar pasta',
    'Add file(s)' => 'Adicionar arquivo(s)',
    'Adds files module to this space.' => 'Adicionar o módulo de arquivos para este espaço.',
    'Adds files module to your profile.' => 'Adicionar o módulo de arquivos para o seu perfil.',
    'Archive %filename% could not be extracted.' => 'Arquivo %filename% não pôde ser extraído.',
    'Archive (zip) support is not enabled.' => 'Suporte a Arquivo (ZIP) não está ativado.',
    'Close' => 'Fechar',
    'Could not save file %title%. ' => 'Arquivo %title% não pôde ser salvo.',
    'Creator' => 'Criador',
    'Delete' => 'Apagar',
    'Disable archive (ZIP) support' => 'Desabilitar suporte a Arquivo (ZIP)',
    'Do you really want to delete this %number% item(s) with all subcontent?' => 'Você realmente quer apagar este(s) %número% item(s) com todo seu conteúdo?',
    'Download' => 'Baixar',
    'Download ZIP' => 'Baixar ZIP',
    'Edit' => 'Editar',
    'Edit directory' => 'Editar pasta',
    'File' => 'Arquivo',
    'Files' => 'Arquivos',
    'Folder' => 'Pasta',
    'Folder options' => 'Opções da Pasta',
    'Folder should not start or end with blank space.' => 'Pasta não pode iniciar ou terminar com espaço em branco.',
    'Insufficient rights to execute this action.' => 'Permissões insuficientes para executar esta ação.',
    'Invalid parameter.' => 'Parâmetro inválido.',
    'Move' => 'Mover.',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Não é possível mover para o mesmo dirtório.por favro localize outro diretório para %title%.',
    'Name' => 'Nome',
    'No valid items were selected to move.' => 'Não há itens selecionados.',
    'Open' => 'Abrir',
    'Opening archive failed with error code %code%.' => 'Falha ao abrir o arquivo. Código %code%',
    'Please select a valid destination folder for %title%.' => 'por favor, selecione um diretório de destino válido para %title%.',
    'Save' => 'Salvar',
    'Selected items...' => 'Itens selecionados...',
    'Show Post' => 'Exibir Post',
    'Size' => 'Tamanho',
    'The archive could not be created.' => 'O arquivo não pôde ser criado.',
    'The folder %filename% already exists. Contents have been overwritten.' => 'O diretório %filename% já existe. Seu conteúdo será sobrescrito.',
    'The folder with the id %id% does not exist.' => 'O diretório %id% não existe.',
    'This folder is empty.' => 'Esta pasta está vazia.',
    'Unfortunately you have no permission to upload/edit files.' => 'Infelizmente, você não tem permissão para transferir/editar arquivos.',
    'Updated' => 'Atualizado',
    'Upload' => 'Transferir',
    'Upload ZIP' => 'Transferir ZIP',
    'Upload files or create a subfolder with the buttons on the top.' => 'Transfira arquivos ou crie um sub diretório usando os botões na parte superior.',
    'Upload files to the stream to fill this folder.' => 'Transfira arquivos por stream para este diretório.',
    'ZIP all' => 'ZIP todos',
    'ZIP selected' => 'ZIP selecionado',
    'changed:' => 'alterado:',
    'created:' => 'criado:',
];
