<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>File</strong> download url' => '',
    '<strong>File</strong> url' => '',
    '<strong>Folder</strong> url' => '',
    'A file with that name already exists in this folder.' => '',
    'An error occurred while creating folder {folder}.' => '',
    'An error occurred while unpacking {filename}.' => '',
    'Could not find folder with id: %id%' => '',
    'Destination folder not found!' => '',
    'Display Url' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Folder {name} can\'t be moved to itself!' => '',
    'Folder {name} given folder is not editable!' => '',
    'Make Private' => '',
    'Make Public' => '',
    'Moving to the same folder is not valid.' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Root' => '',
    'Size: {size}' => '',
    'Some files could not be imported: ' => '',
    'Some files could not be moved: ' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This file is private.' => '',
    'This file is public.' => '',
    'This folder is private.' => '',
    'This folder is public.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP support is not enabled.' => '',
    '%filename% has invalid extension and was skipped.' => '%filename% possui extensão inválida e foi ignorada.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Confirme</strong> excluir arquivo',
    '<strong>Create</strong> folder' => '<strong>Criar</strong> pasta',
    '<strong>Edit</strong> file' => '<strong>Editar</strong> arquivo',
    '<strong>Edit</strong> folder' => '<strong>Editar</strong> pasta',
    '<strong>Files</strong> module configuration' => 'Configuração do módulo de <strong>Arquivos</strong>',
    '<strong>Move</strong> files' => '<strong>Mover</strong> arquivos',
    'A folder with this name already exists.' => 'Já existe uma pasta com esse nome.',
    'Add directory' => 'Adicionar pasta',
    'Add file(s)' => 'Adicionar arquivo(s)',
    'Adds files module to this space.' => 'Adicionar o módulo de arquivos para este espaço.',
    'Adds files module to your profile.' => 'Adicionar o módulo de arquivos para o seu perfil.',
    'Archive %filename% could not be extracted.' => 'Arquivo %filename% não pôde ser extraído.',
    'Cannot edit non existing file.' => 'Não é possível editar um arquivo inexistente.',
    'Creator' => 'Criador',
    'Delete' => 'Apagar',
    'Disable archive (ZIP) support' => 'Desabilitar suporte a Arquivo (ZIP)',
    'Download' => 'Baixar',
    'Download ZIP' => 'Baixar ZIP',
    'Edit' => 'Editar',
    'Edit directory' => 'Editar pasta',
    'File' => 'Arquivo',
    'Files' => 'Arquivos',
    'Folder' => 'Pasta',
    'Folder should not start or end with blank space.' => 'Pasta não pode iniciar ou terminar com espaço em branco.',
    'Insufficient rights to execute this action.' => 'Permissões insuficientes para executar esta ação.',
    'Likes/Comments' => 'Curtidas/Comentários',
    'Move' => 'Mover.',
    'Name' => 'Nome',
    'Open' => 'Abrir',
    'Opening archive failed with error code %code%.' => 'Falha ao abrir o arquivo. Código %code%',
    'Please select a valid destination folder for %title%.' => 'Por favor, selecione um diretório de destino válido para %title%.',
    'Selected items...' => 'Itens selecionados...',
    'Show Post' => 'Exibir Post',
    'Size' => 'Tamanho',
    'This folder is empty.' => 'Esta pasta está vazia.',
    'Unfortunately you have no permission to upload/edit files.' => 'Infelizmente, você não tem permissão para transferir/editar arquivos.',
    'Updated' => 'Atualizado',
    'Upload files or create a subfolder with the buttons on the top.' => 'Transfira arquivos ou crie uma subpasta usando os botões na parte superior.',
    'Upload files to the stream to fill this folder.' => 'Transfira arquivos ao stream para preencher esta pasta.',
    'ZIP selected' => 'ZIP selecionado',
];
