<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '',
    'Import Zip' => '',
    'Replace existing files' => '',
    'This file is only visible for you and your friends.' => '',
    'This file is protected.' => '',
    'This folder is only visible for you and your friends.' => '',
    'This folder is protected.' => '',
    'Upload behaviour for existing file names' => '',
    'Use of file indexes for already existing files' => '',
    '%filename% has invalid extension and was skipped.' => '%filename% heeft een ongeldige extensie en is overgeslagen.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Verwijder</strong> bestand',
    '<strong>Create</strong> folder' => '<strong>Maak</strong> map',
    '<strong>Edit</strong> file' => '<strong>Bewerk</strong> bestand',
    '<strong>Edit</strong> folder' => '<strong>Bewerk</strong> map',
    '<strong>File</strong> download url' => '<strong>Bestand</strong> download url',
    '<strong>File</strong> url' => '<strong>Bestand</strong> url',
    '<strong>Files</strong> module configuration' => '<strong>Bestanden</strong> module instellingen',
    '<strong>Folder</strong> url' => '<strong>Map</strong> url',
    '<strong>Move</strong> files' => '<strong>Verplaats</strong> bestanden',
    'A file with that name already exists in this folder.' => 'Een bestand met die naam bestaat al in deze map.',
    'A folder with this name already exists.' => 'Een map met deze naam bestaat al.',
    'Add directory' => 'Map toevoegen',
    'Add file(s)' => 'Bestand(en) toevoegen',
    'Adds files module to this space.' => 'Bestanden module toevoegen aan deze space.',
    'Adds files module to your profile.' => 'Voegt de bestanden module toe aan je profiel.',
    'An error occurred while creating folder {folder}.' => 'Er is een fout opgetreden bij het maken van map {folder}.',
    'An error occurred while unpacking {filename}.' => 'Er is een fout opgetreden bij het uitpakken van {filename}.',
    'Archive %filename% could not be extracted.' => 'Archief  %filename%  kan niet worden uitgepakt..',
    'Cannot edit non existing file.' => 'Bestand bestaat niet.',
    'Could not find folder with id: %id%' => 'Kan geen map met id  %id% vinden:',
    'Creator' => 'Maker',
    'Delete' => 'Verwijderen',
    'Destination folder not found!' => 'Bestemmingsmap niet gevonden!',
    'Disable archive (ZIP) support' => 'Schakel archief (ZIP) ondersteuning uit',
    'Display Url' => 'Toon Url',
    'Do you really want to delete this {number} item(s) with all subcontent?' => 'Wilt u dit {number} item (s) met alle inhoud erin verwijderen?',
    'Download' => 'Download',
    'Download ZIP' => 'Download ZIP',
    'Edit' => 'Bewerk',
    'Edit directory' => 'Map bewerken',
    'File' => 'Bestand',
    'Files' => 'Bestanden',
    'Files from the stream' => 'Bestanden van de berichtenstroom',
    'Folder' => 'Map',
    'Folder should not start or end with blank space.' => 'Naam van de map mag niet beginnen of eindigen met een spatie.',
    'Folder {name} can\'t be moved to itself!' => 'Map {name} kan niet naar zichzelf worden verplaatst!',
    'Folder {name} given folder is not editable!' => 'Naam {name} van deze map is niet bewerkbaar!',
    'Likes/Comments' => 'Vind ik leuk / Commentaar',
    'Make Private' => 'Privé maken',
    'Make Public' => 'Openbaar maken',
    'Move' => 'Verplaatsen',
    'Moving to the same folder is not valid.' => 'Het verplaatsen naar dezelfde map is niet mogelijk.',
    'Moving to this folder is invalid.' => 'Het verplaatsen naar deze map is niet mogelijk.',
    'Name' => 'Naam',
    'Open' => 'Open',
    'Open file folder' => 'Open bestandsmap',
    'Opening archive failed with error code %code%.' => 'Opening van archief is mislukt,  foutcode %code%.',
    'Please select a valid destination folder for %title%.' => 'Selecteer een geldige bestemmingsmap voor %title%.',
    'Root' => 'Root',
    'Selected items...' => 'Geselecteerde items ...',
    'Show Post' => 'Toon bericht',
    'Size' => 'Grootte',
    'Size: {size}' => 'Grootte: {size}',
    'Some files could not be imported: ' => 'Sommige bestanden kunnen niet worden geïmporteerd:',
    'Some files could not be moved: ' => 'Sommige bestanden kunnen niet worden verplaatst:',
    'The root folder is the entry point that contains all available files.' => 'De hoofdmap is het beginpunt dat alle beschikbare bestanden bevat.',
    'This file is private.' => 'Dit bestand is privé.',
    'This file is public.' => 'Dit bestand is openbaar.',
    'This folder is empty.' => 'Deze map is leeg.',
    'This folder is private.' => 'Deze map is privé',
    'This folder is public.' => 'Deze map is openbaar.',
    'Unfortunately you have no permission to upload/edit files.' => 'Helaas ontbreekt toestemming om bestanden te uploaden of te  bewerken.',
    'Updated' => 'Bijgewerkt',
    'Upload files or create a subfolder with the buttons on the top.' => 'Upload bestanden of maak een submap met de knoppen bovenaan.',
    'Upload files to the stream to fill this folder.' => 'Upload bestanden naar de berichtenstroom om deze map te vullen.',
    'You can find all files that have been posted to this stream here.' => 'U kunt hier alle bestanden vinden die in deze berichtenstroom zijn geplaatst.',
    'ZIP selected' => 'ZIPpen',
    'ZIP support is not enabled.' => 'ZIP-ondersteuning is niet ingeschakeld.',
];
