<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%title% was replaced by a newer version.' => '',
    '/ (root)' => '',
    '<strong>Confirm</strong> delete file' => '',
    '<strong>Create</strong> folder' => '',
    '<strong>Edit</strong> file' => '',
    '<strong>Edit</strong> folder' => '',
    '<strong>Files</strong> module configuration' => '',
    '<strong>Move</strong> files' => '',
    'A folder with this name already exists.' => '',
    'Adds files module to this space.' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'Cannot edit non existing file.' => '',
    'Creator' => '',
    'Disable archive (ZIP) support' => '',
    'Do you really want to delete this %number% item(s) with all subcontent?' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Download ZIP' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Likes/Comments' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Root' => '',
    'Show Image' => '',
    'Size: {size}' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    'ZIP support is not enabled.' => '',
    'changed:' => '',
    'created:' => '',
    'Add directory' => 'Přidat složku',
    'Add file(s)' => 'Přidat soubor(y)',
    'Adds files module to your profile.' => 'Přidá modul Soubory do vašeho profilu.',
    'Close' => 'Zavřít',
    'Could not save file %title%. ' => 'Nebylo možné uložit soubor %title%.',
    'Delete' => 'Smazat',
    'Download' => 'Stáhnout',
    'Edit' => 'Upravit',
    'Edit directory' => 'Upravit složku',
    'File' => 'Soubor',
    'Files' => 'Soubory',
    'Folder' => 'Složka',
    'Insufficient rights to execute this action.' => 'K provedení této akce nemáte dostatečná oprávnění.',
    'Move' => 'Přesunout',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Nelze přesouvat do stejné složky. Vyberte jiný cíl pro přesun %title%.',
    'Name' => 'Název',
    'No valid items were selected to move.' => 'Nebyly zvoleny žádné soubory či složky pro přesun.',
    'Open' => 'Otevřít',
    'Opening archive failed with error code %code%.' => 'Nelze otevřít archív (chyba: %code%).',
    'Please select a valid destination folder for %title%.' => 'Vyberte prosím cílovou složku pro %title%.',
    'Save' => 'Uložit',
    'Selected items...' => 'Možnost akce s vybranými položkami...',
    'Show Post' => 'Zobrazit příspěvek',
    'Size' => 'Velikost',
    'This folder is empty.' => 'Tato složka je prázdná.',
    'Unfortunately you have no permission to upload/edit files.' => 'Bohužel nemáte oprávnění nahrávat či měnit soubory.',
    'Updated' => 'Aktualizováno',
];
