<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' The folder %filename% could not be saved.' => '',
    '%filename% has invalid extension and was skipped.' => '',
    '%title% was replaced by a newer version.' => '',
    '/ (root)' => '',
    '<strong>Confirm</strong> delete file' => '',
    '<strong>Create</strong> folder' => '',
    '<strong>Edit</strong> folder' => '',
    '<strong>Files</strong> module configuration' => '',
    '<strong>Move</strong> files' => '',
    'A folder with this name already exists.' => '',
    'Adds files module to this space.' => '',
    'Archive %filename% could not be extracted.' => '',
    'Archive (zip) support is not enabled.' => '',
    'Creator' => '',
    'Disable archive (ZIP) support' => '',
    'Do you really want to delete this %number% item(s) with all subcontent?' => '',
    'Download ZIP' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Upload ZIP' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    'changed:' => '',
    'created:' => '',
    'Add directory' => 'Přidat složku',
    'Add file(s)' => 'Přidat soubor(y)',
    'Adds files module to your profile.' => 'Přidá modul Soubory do vašeho profilu.',
    'Close' => 'Zavřít',
    'Could not save file %title%. ' => 'Nebylo možné uložit soubor %title%.',
    'Delete' => 'Smazat',
    'Download' => 'Stáhnout',
    'Edit' => 'Upravit',
    'Edit directory' => 'Upravit složku',
    'File' => 'Soubor',
    'Files' => 'Soubory',
    'Folder' => 'Složka',
    'Folder options' => 'Možnosti složky',
    'Insufficient rights to execute this action.' => 'K provedení této akce nemáte dostatečná oprávnění.',
    'Invalid parameter.' => 'Neplatný parametr.',
    'Move' => 'Přesunout',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Nelze přesouvat do stejné složky. Vyberte jiný cíl pro přesun %title%.',
    'Name' => 'Název',
    'No valid items were selected to move.' => 'Nebyly zvoleny žádné soubory či složky pro přesun.',
    'Open' => 'Otevřít',
    'Opening archive failed with error code %code%.' => 'Nelze otevřít archív (chyba: %code%).',
    'Please select a valid destination folder for %title%.' => 'Vyberte prosím cílovou složku pro %title%.',
    'Save' => 'Uložit',
    'Selected items...' => 'Možnost akce s vybranými položkami...',
    'Show' => 'Zobrazit',
    'Show Post' => 'Zobrazit příspěvek',
    'Size' => 'Velikost',
    'The archive could not be created.' => 'Nebylo možné vytvořit archív.',
    'The folder %filename% already exists. Contents have been overwritten.' => 'Složka s názvem %filename% již existuje, obsah byl přepsán.',
    'The folder with the id %id% does not exist.' => 'Složka s id %id% neexistuje.',
    'This folder is empty.' => 'Tato složka je prázdná.',
    'Unfortunately you have no permission to upload/edit files.' => 'Bohužel nemáte oprávnění nahrávat či měnit soubory.',
    'Updated' => 'Aktualizováno',
    'Upload' => 'Nahrát',
    'root' => 'hlavní složka',
];
