<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> file' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'An internal error occurred. Could not load default folder containing all posted files, database not properly initialized.' => '',
    'An internal error occurred. Could not load root folder, database not properly initialized.' => '',
    'Cannot edit non existing file.' => '',
    'Collapse' => '',
    'Created at:' => '',
    'Created by:' => '',
    'Edit the file description...' => '',
    'Edit the folder description...' => '',
    'Filesize:' => '',
    'Last edited at:' => '',
    'Last edited by:' => '',
    'Likes/Comments' => '',
    'Open directory!' => '',
    'Open parent directory!' => '',
    'Schließen' => '',
    'Show Image' => '',
    'Show all files' => '',
    'Show complete file preview' => '',
    'Show on Wall' => '',
    'This folder is still empty.' => '',
    ' The folder %filename% could not be saved.' => 'Das Verzeichnis %filename% konnte nicht gespeichert werden.',
    '%filename% has invalid extension and was skipped.' => '%filename% hat eine unerlaubte Dateieendung und wurde übersprungen.',
    '%title% was replaced by a newer version.' => '%title% wurde durch eine neuere Version ersetzt.',
    '/ (root)' => '/ (Stammverzeichnis)',
    '<strong>Confirm</strong> delete file' => 'Löschen der Datei <strong>bestätigen</strong>',
    '<strong>Create</strong> folder' => 'Ordner <strong>erstellen</strong>',
    '<strong>Edit</strong> folder' => 'Ordner <strong>bearbeiten</strong>',
    '<strong>Files</strong> module configuration' => '<strong>Dateimodul</strong> Konfiguration',
    '<strong>Move</strong> files' => 'Dateien <strong>verschieben</strong>',
    'A folder with this name already exists.' => 'Ein Ordner mit diesem namen ist bereits vorhanden.',
    'Add directory' => 'Neuer Ordner',
    'Add file(s)' => 'Dateien hochladen',
    'Adds files module to this space.' => 'Erweitert den Space um ein Datei-Ablage-Modul',
    'Adds files module to your profile.' => 'Erweitert dein Profil um ein Datei-Ablage-Modul',
    'Archive %filename% could not be extracted.' => 'Archiv %filename% konnte nicht entpackt werden.',
    'Archive (zip) support is not enabled.' => 'Komprimierung (ZIP) ist nicht aktiviert.',
    'Close' => 'Schliessen',
    'Could not save file %title%. ' => 'Die Datei %title% konnte nicht gespeichert werden',
    'Creator' => 'Ersteller',
    'Delete' => 'Löschen',
    'Disable archive (ZIP) support' => 'Komprmierung (ZIP) deaktivieren',
    'Do you really want to delete this %number% item(s) with all subcontent?' => 'Möchtes du wirklich %number% Element(e) einschließlich ihrer Unterlemente löschen?',
    'Download' => 'Herunterladen',
    'Download ZIP' => 'Download ZIP',
    'Edit' => 'Bearbeiten',
    'Edit directory' => 'Ordner bearbeiten',
    'File' => 'Datei',
    'Files' => 'Dateien',
    'Folder' => 'Ordner',
    'Folder options' => 'Ordner Optionen',
    'Folder should not start or end with blank space.' => 'Die Bezeichnung des Ordners darf nicht mit einem Leerzeichen beginnen oder enden.',
    'Insufficient rights to execute this action.' => 'Keine ausreichenden Rechte um diese Aktion auszuführen.',
    'Invalid parameter.' => 'Unzulässiger Parameter.',
    'Move' => 'Verschieben',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Verschieben in das selbe Verzeichnis nicht möglich. Bitte ein übergeordnetes Verzeichnis für %title% auswählen.',
    'Name' => 'Name',
    'No valid items were selected to move.' => 'Keine gültigen Elemente zum Verschieben ausgewählt.',
    'Open' => 'Öffnen',
    'Opening archive failed with error code %code%.' => 'Öffnen des Archivs mit Fehlercode %code% fehlgeschlagen.',
    'Please select a valid destination folder for %title%.' => 'Bitte ein gültiges Zielverzeichnis für %title% auswählen.',
    'Save' => 'Speichern',
    'Selected items...' => 'Ausgewählte Elemente...',
    'Show Post' => 'Eintrag anzeigen',
    'Size' => 'Größe',
    'The archive could not be created.' => 'Das Archiv konnte nicht erstellt werden',
    'The folder %filename% already exists. Contents have been overwritten.' => 'Das Verzeichnis %filename% ist bereits vorhaden. Der Inhalt wurde überschrieben.',
    'The folder with the id %id% does not exist.' => 'Das Verzeichnis mit der ID %id% ist nicht vorhanden.',
    'This folder is empty.' => 'Dieser Ordner ist leer.',
    'Unfortunately you have no permission to upload/edit files.' => 'Du hast keine Erlaubnis zum hochladen oder bearbeiten von Dateien.',
    'Updated' => 'Aktualisiert',
    'Upload' => 'Hochladen',
    'Upload ZIP' => 'Hochladen ZIP',
    'Upload files or create a subfolder with the buttons on the top.' => 'Mit den obigen Schaltflächen Dateien hochladen oder Unterordner erstellen.',
    'Upload files to the stream to fill this folder.' => 'Poste Dateien im Stream, um diesen Ordner zu füllen.',
    'ZIP all' => 'Alle komprimieren',
    'ZIP selected' => 'Ausgewählte Komprimieren',
    'changed:' => 'geändert:',
    'created:' => 'erstellt:',
];
