<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>File</strong> download url' => '',
    '<strong>File</strong> url' => '',
    '<strong>Folder</strong> url' => '',
    'A file with that name already exists in this folder.' => '',
    'An error occurred while creating folder {folder}.' => '',
    'An error occurred while unpacking {filename}.' => '',
    'Could not find folder with id: %id%' => '',
    'Destination folder not found!' => '',
    'Display Url' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Folder {name} can\'t be moved to itself!' => '',
    'Folder {name} given folder is not editable!' => '',
    'Make Private' => '',
    'Make Public' => '',
    'Moving to the same folder is not valid.' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Root' => '',
    'Size: {size}' => '',
    'Some files could not be imported: ' => '',
    'Some files could not be moved: ' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This file is private.' => '',
    'This file is public.' => '',
    'This folder is private.' => '',
    'This folder is public.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP support is not enabled.' => '',
    '%filename% has invalid extension and was skipped.' => '%filename% hat eine unerlaubte Dateieendung und wurde übersprungen.',
    '/ (root)' => '/ (Stammverzeichnis)',
    '<strong>Confirm</strong> delete file' => 'Löschen der Datei <strong>bestätigen</strong>',
    '<strong>Create</strong> folder' => 'Ordner <strong>erstellen</strong>',
    '<strong>Edit</strong> file' => 'Datei <strong>bearbeiten</strong>',
    '<strong>Edit</strong> folder' => 'Ordner <strong>bearbeiten</strong>',
    '<strong>Files</strong> module configuration' => '<strong>Dateimodul</strong> Konfiguration',
    '<strong>Move</strong> files' => 'Dateien <strong>verschieben</strong>',
    'A folder with this name already exists.' => 'Ein Ordner mit diesem namen ist bereits vorhanden.',
    'Add directory' => 'Neuer Ordner',
    'Add file(s)' => 'Dateien hochladen',
    'Adds files module to this space.' => 'Erweitert den Space um ein Datei-Ablage-Modul',
    'Adds files module to your profile.' => 'Erweitert dein Profil um ein Datei-Ablage-Modul',
    'Archive %filename% could not be extracted.' => 'Archiv %filename% konnte nicht entpackt werden.',
    'Cannot edit non existing file.' => 'EIne nicht vorhandene Datei kann nicht editiert werden.',
    'Creator' => 'Ersteller',
    'Delete' => 'Löschen',
    'Disable archive (ZIP) support' => 'Komprmierung (ZIP) deaktivieren',
    'Download' => 'Herunterladen',
    'Download ZIP' => 'Download ZIP',
    'Edit' => 'Bearbeiten',
    'Edit directory' => 'Ordner bearbeiten',
    'File' => 'Datei',
    'Files' => 'Dateien',
    'Folder' => 'Ordner',
    'Folder should not start or end with blank space.' => 'Die Bezeichnung des Ordners darf nicht mit einem Leerzeichen beginnen oder enden.',
    'Insufficient rights to execute this action.' => 'Keine ausreichenden Rechte um diese Aktion auszuführen.',
    'Likes/Comments' => 'Gefällt mir / Kommentare',
    'Move' => 'Verschieben',
    'Name' => 'Name',
    'Open' => 'Öffnen',
    'Opening archive failed with error code %code%.' => 'Öffnen des Archivs mit Fehlercode %code% fehlgeschlagen.',
    'Please select a valid destination folder for %title%.' => 'Bitte ein gültiges Zielverzeichnis für %title% auswählen.',
    'Selected items...' => 'Ausgewählte Elemente...',
    'Show Post' => 'Eintrag anzeigen',
    'Size' => 'Größe',
    'This folder is empty.' => 'Dieser Ordner ist leer.',
    'Unfortunately you have no permission to upload/edit files.' => 'Du hast keine Erlaubnis zum hochladen oder bearbeiten von Dateien.',
    'Updated' => 'Aktualisiert',
    'Upload files or create a subfolder with the buttons on the top.' => 'Mit den obigen Schaltflächen Dateien hochladen oder Unterordner erstellen.',
    'Upload files to the stream to fill this folder.' => 'Dateien in Stream hochladen, um diesen Ordner zu füllen.',
    'ZIP selected' => 'Ausgewählte komprimieren',
];
