<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Root' => '',
    'Size: {size}' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP support is not enabled.' => '',
    '%title% was replaced by a newer version.' => '%title% wurde durch eine neuere Version ersetzt.',
    '/ (root)' => '/ (Stammverzeichnis)',
    '<strong>Confirm</strong> delete file' => 'Löschen der Datei <strong>bestätigen</strong>',
    '<strong>Create</strong> folder' => 'Ordner <strong>erstellen</strong>',
    '<strong>Edit</strong> file' => 'Datei <strong>bearbeiten</strong>',
    '<strong>Edit</strong> folder' => 'Ordner <strong>bearbeiten</strong>',
    '<strong>Files</strong> module configuration' => '<strong>Dateimodul</strong> Konfiguration',
    '<strong>Move</strong> files' => 'Dateien <strong>verschieben</strong>',
    'A folder with this name already exists.' => 'Ein Ordner mit diesem namen ist bereits vorhanden.',
    'Add directory' => 'Neuer Ordner',
    'Add file(s)' => 'Dateien hochladen',
    'Adds files module to this space.' => 'Erweitert den Space um ein Datei-Ablage-Modul',
    'Adds files module to your profile.' => 'Erweitert dein Profil um ein Datei-Ablage-Modul',
    'An internal error occurred. Could not find folder with id: %id%' => 'Ein interner Fehler ist aufgetreten. Der Ordner mit der ID %id% konnte nicht gefunden werden.',
    'Cannot edit non existing file.' => 'EIne nicht vorhandene Datei kann nicht editiert werden.',
    'Close' => 'Schliessen',
    'Could not save file %title%. ' => 'Die Datei %title% konnte nicht gespeichert werden',
    'Creator' => 'Ersteller',
    'Delete' => 'Löschen',
    'Disable archive (ZIP) support' => 'Komprmierung (ZIP) deaktivieren',
    'Do you really want to delete this %number% item(s) with all subcontent?' => 'Möchtes du wirklich %number% Element(e) einschließlich ihrer Unterlemente löschen?',
    'Download' => 'Herunterladen',
    'Download ZIP' => 'Download ZIP',
    'Edit' => 'Bearbeiten',
    'Edit directory' => 'Ordner bearbeiten',
    'File' => 'Datei',
    'Files' => 'Dateien',
    'Folder' => 'Ordner',
    'Folder should not start or end with blank space.' => 'Die Bezeichnung des Ordners darf nicht mit einem Leerzeichen beginnen oder enden.',
    'Insufficient rights to execute this action.' => 'Keine ausreichenden Rechte um diese Aktion auszuführen.',
    'Likes/Comments' => 'Gefällt mir / Kommentare',
    'Move' => 'Verschieben',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Verschieben in das selbe Verzeichnis nicht möglich. Bitte ein übergeordnetes Verzeichnis für %title% auswählen.',
    'Name' => 'Name',
    'No valid items were selected to move.' => 'Keine gültigen Elemente zum Verschieben ausgewählt.',
    'Open' => 'Öffnen',
    'Opening archive failed with error code %code%.' => 'Öffnen des Archivs mit Fehlercode %code% fehlgeschlagen.',
    'Please select a valid destination folder for %title%.' => 'Bitte ein gültiges Zielverzeichnis für %title% auswählen.',
    'Save' => 'Speichern',
    'Selected items...' => 'Ausgewählte Elemente...',
    'Show Image' => 'Bild anzeigen',
    'Show Post' => 'Eintrag anzeigen',
    'Size' => 'Größe',
    'This folder is empty.' => 'Dieser Ordner ist leer.',
    'Unfortunately you have no permission to upload/edit files.' => 'Du hast keine Erlaubnis zum hochladen oder bearbeiten von Dateien.',
    'Updated' => 'Aktualisiert',
    'Upload files or create a subfolder with the buttons on the top.' => 'Mit den obigen Schaltflächen Dateien hochladen oder Unterordner erstellen.',
    'Upload files to the stream to fill this folder.' => 'Dateien in Stream hochladen, um diesen Ordner zu füllen.',
    'ZIP all' => 'Alle komprimieren',
    'ZIP selected' => 'Ausgewählte komprimieren',
    'changed:' => 'geändert:',
    'created:' => 'erstellt:',
];
