<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> file' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'Cannot edit non existing file.' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Likes/Comments' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Root' => '',
    'Show Image' => '',
    'Size: {size}' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP support is not enabled.' => '',
    '%title% was replaced by a newer version.' => 'توسط ورژن جديد جايگذاري شد %title%',
    '/ (root)' => '/ (ريشه اصلي)',
    '<strong>Confirm</strong> delete file' => '<strong>حذف فايل را تاييد كنيد</strong>',
    '<strong>Create</strong> folder' => '<strong>پوشه اي بسازيد</strong>',
    '<strong>Edit</strong> folder' => '<strong>ويرايش پوشه</strong>',
    '<strong>Files</strong> module configuration' => '<strong>ويرايش ماژول فايل ها</strong>',
    '<strong>Move</strong> files' => '<strong>انتقال و حركت دادن فايل ها</strong>',
    'A folder with this name already exists.' => 'پوشه اي با همين اسم موجود است',
    'Add directory' => 'اضافه كردن فهرست راهنما',
    'Add file(s)' => 'اضافه كردن فايل (ها)',
    'Adds files module to this space.' => 'اضافه كردن ماژول فايل ها به اين انجمن',
    'Adds files module to your profile.' => 'اضافه كردن ماژول فايل ها به پروفايل',
    'Close' => 'بستن',
    'Could not save file %title%. ' => 'نتوانست ذخيره شود %title% عنوان',
    'Creator' => 'سازنده',
    'Delete' => 'حذف',
    'Disable archive (ZIP) support' => 'فعالسازي پشتيباني آرشيو كردن فايل',
    'Do you really want to delete this %number% item(s) with all subcontent?' => 'آيا مي خواهيد همه اين فايل ها و زيرشاخه هايشان را حذف كنيد؟',
    'Download' => 'بارگيري',
    'Download ZIP' => 'بارگيري زيپ',
    'Edit' => 'ويرايش',
    'Edit directory' => 'ويرايش فهرست راهنما',
    'File' => 'فايل',
    'Files' => 'فايل ها',
    'Folder' => 'پوشه',
    'Folder should not start or end with blank space.' => 'نام پوشه نبايد با فاصله شروع يا ختم شود',
    'Insufficient rights to execute this action.' => 'شما حق انجام اين عمل را نداريد',
    'Move' => 'حركت دادن',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'حركت دادن فايل به همان پوشه امكان پذير نيست',
    'Name' => 'نام',
    'No valid items were selected to move.' => 'هيچ آيتم معتبري براي حركت دادن انتخاب نشده است',
    'Open' => 'بازكردن',
    'Opening archive failed with error code %code%.' => 'باز كردن فايل فشره انجام نشد . كد اراور :  %code%',
    'Please select a valid destination folder for %title%.' => 'وارد كنيد %title% لطفا مقصدي معتبر براي انتقال فايل',
    'Save' => 'ذخيره',
    'Selected items...' => 'آيتم هاي انتخاب شده',
    'Show Post' => 'نمايش پست',
    'Size' => 'اندازه',
    'This folder is empty.' => 'اين پوشه خالي است',
    'Unfortunately you have no permission to upload/edit files.' => 'متاسفانه شما اجازه آپلود يا ويرايش فايل ها را نداريد',
    'Updated' => 'بروز رساني شده',
    'Upload files or create a subfolder with the buttons on the top.' => 'آپلود فايل يا ايجاد يك زير شاخه با دكمه هاي بالا',
    'Upload files to the stream to fill this folder.' => 'استريم كردن فايل ها تا اين پوشه پر شود',
    'ZIP all' => 'همه را فشرده كن',
    'ZIP selected' => 'فايل انتخاب شده را زيپ كن',
    'changed:' => 'تغيير :',
    'created:' => 'ايجاد :',
];
