<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '',
    'Import Zip' => '',
    'Replace existing files' => '',
    'This file is only visible for you and your friends.' => '',
    'This file is protected.' => '',
    'This folder is only visible for you and your friends.' => '',
    'This folder is protected.' => '',
    'Upload behaviour for existing file names' => '',
    'Use of file indexes for already existing files' => '',
    '%filename% has invalid extension and was skipped.' => 'Bỏ qua %filename% vì phần mở rộng không hợp lệ.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Xác nhận</strong> xóa file',
    '<strong>Create</strong> folder' => '<strong>Tạo</strong> thư mục',
    '<strong>Edit</strong> file' => '<strong>Chỉnh sửa</strong> file',
    '<strong>Edit</strong> folder' => '<strong>Chỉnh sửa</strong> thư mục',
    '<strong>File</strong> download url' => 'Địa chỉ download <strong>file</strong>',
    '<strong>File</strong> url' => 'Địa chỉ <strong>file</strong>',
    '<strong>Files</strong> module configuration' => 'Cấu hình module <strong>Files</strong>',
    '<strong>Folder</strong> url' => 'Địa chỉ <strong>thư mục</strong> ',
    '<strong>Move</strong> files' => '<strong>Di chuyển</strong> files',
    'A file with that name already exists in this folder.' => 'Tên file đã tồn tại trong thư mục này.',
    'A folder with this name already exists.' => 'Tên thư mục đã tồn tại',
    'Add directory' => 'Thêm thư mục',
    'Add file(s)' => 'Thêm file (cho phép nhiều file)',
    'Adds files module to this space.' => 'Thêm module files vào phòng làm việc này. ',
    'Adds files module to your profile.' => 'Thêm module files vào trang cá nhân của bạn',
    'An error occurred while creating folder {folder}.' => 'Có lỗi xảy ra khi tạo thư mục {folder}.',
    'An error occurred while unpacking {filename}.' => 'Có lỗi xảy ra khi giải nén {filename}.',
    'Archive %filename% could not be extracted.' => 'File nén %filename% không thể được giải nén.',
    'Cannot edit non existing file.' => 'Không thể sửa file không tồn tại.',
    'Could not find folder with id: %id%' => 'Không thể tìm thư mục có id: %id%',
    'Creator' => 'Người tạo',
    'Delete' => 'Xóa',
    'Destination folder not found!' => 'Không tìm thấy thư mục đích!',
    'Disable archive (ZIP) support' => 'Ngưng kích hoạt hỗ trợ nén file (zip)',
    'Display Url' => 'Hiển thị địa chỉ (URL)',
    'Do you really want to delete this {number} item(s) with all subcontent?' => 'Bạn thực sự muốn xóa {number} hạng mục và toàn bộ nội dung chứa trong đó?',
    'Download' => 'Download',
    'Download ZIP' => 'Download file nén (zip)',
    'Edit' => 'Chỉnh sửa',
    'Edit directory' => 'Chỉnh sửa thư mục',
    'File' => 'File',
    'Files' => 'Files',
    'Files from the stream' => 'Files từ dòng thời gian',
    'Folder' => 'Thư mục',
    'Folder should not start or end with blank space.' => 'Thư mục không nên bắt đầu hoặc kết thúc bằng khoảng trống',
    'Folder {name} can\'t be moved to itself!' => 'Thư mục {name} không thể được di chuyển tới chính nó!',
    'Folder {name} given folder is not editable!' => 'Thư mục {name} không thể được chỉnh sửa!',
    'Likes/Comments' => 'Likes/Comments',
    'Make Private' => 'Đưa vào riêng tư',
    'Make Public' => 'Đưa ra công cộng',
    'Move' => 'Di chuyển',
    'Moving to the same folder is not valid.' => 'Không được di chuyển tới cùng thư mục.',
    'Moving to this folder is invalid.' => 'Không được di chuyển tới thư mục này.',
    'Name' => 'Tên',
    'Open' => 'Mở',
    'Open file folder' => 'Mở thư mục tệp',
    'Opening archive failed with error code %code%.' => 'Mở file nén thất bại với mã lỗi %code%.',
    'Please select a valid destination folder for %title%.' => 'Vui lòng chọn một thư mục đích cho %title%.',
    'Root' => 'Thư mục gốc',
    'Selected items...' => 'Các hạng mục được chọn...',
    'Show Post' => 'Hiển thị post',
    'Size' => 'Kích thước',
    'Size: {size}' => 'Kích thước: {size}',
    'Some files could not be imported: ' => 'Không thể nhập các file:',
    'Some files could not be moved: ' => 'Không thể di chuyển các file:',
    'The root folder is the entry point that contains all available files.' => 'Thư mục gốc là thư mục cấp cao nhất chưa tất cả các file',
    'This file is private.' => 'Đây là file riêng tư.',
    'This file is public.' => 'Đây là file công cộng.',
    'This folder is empty.' => 'Thư mục này rỗng.',
    'This folder is private.' => 'Đây là thư mục riêng tư',
    'This folder is public.' => 'Đây là thư mục công cộng.',
    'Unfortunately you have no permission to upload/edit files.' => 'Rất tiếc, bạn không có quyền upload/chỉnh sửa files.',
    'Updated' => 'Đã cập nhật',
    'Upload files or create a subfolder with the buttons on the top.' => 'Upload file hoặc tạo một thư mục con bằng các click nút ở góc trên',
    'Upload files to the stream to fill this folder.' => 'Upload file lên dòng thời gian để đưa file vào thư mục này.',
    'You can find all files that have been posted to this stream here.' => 'Bạn có thể tìm thấy tất cả các file đã được đăng trên dòng thời gian này ở đây.',
    'ZIP selected' => 'Nén (zip) file được chọn',
    'ZIP support is not enabled.' => 'Chức năng file (zip) chưa được kích hoạt.',
];
