<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Files</strong> module configuration' => '',
    'A folder with this name already exists.' => '',
    'Adds files module to this space.' => '',
    'Archive (zip) support is not enabled.' => '',
    'Disable archive (ZIP) support' => '',
    'Do you really want to delete this %number% item(s) with all subcontent?' => '',
    'Download ZIP' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Upload ZIP' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    'changed:' => '',
    'created:' => '',
    ' The folder %filename% could not be saved.' => 'Nie można zapisać katalogu %filename%.',
    '%filename% has invalid extension and was skipped.' => '%filename% ma nieprawidłowe rozszerzenie i został pominięty.',
    '%title% was replaced by a newer version.' => '%title% zastąpiono nowszą wersją.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Potwierdź</strong> usunięcie pliku',
    '<strong>Create</strong> folder' => '<strong>Utwórz</strong> nowy folder',
    '<strong>Edit</strong> folder' => '<strong>Edytuj</strong> katalog',
    '<strong>Move</strong> files' => '<strong>Przenieś</strong> pliki',
    'Add directory' => 'Dodaj katalog',
    'Add file(s)' => 'Dodaj Plik(i)',
    'Adds files module to your profile.' => 'Dodaje moduł plików do twojego profilu',
    'Archive %filename% could not be extracted.' => 'Nie można rozpakować %filename%.',
    'Close' => 'Zamknij',
    'Could not save file %title%. ' => 'Nie można zapisać %title%.',
    'Creator' => 'Właściciel',
    'Delete' => 'Usuń',
    'Download' => 'Pobierz',
    'Edit' => 'Edycja',
    'Edit directory' => 'Edytuj katalog',
    'File' => 'Plik',
    'Files' => 'Pliki',
    'Folder' => 'Katalog',
    'Folder options' => 'Opcje katalogu',
    'Insufficient rights to execute this action.' => 'Brak wystarczających uprawnień do wykonania tej operacji.',
    'Invalid parameter.' => 'Błędny parametr.',
    'Move' => 'Przenieś',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Przenoszenie do tego samego katalogu jest niemożliwe. Wybierz poprawny katalog nadrzędny dla %title%.',
    'Name' => 'Nazwa',
    'No valid items were selected to move.' => 'Nie zaznaczono poprawnych elementów do przeniesienia.',
    'Open' => 'Otwórz',
    'Opening archive failed with error code %code%.' => 'Otwarcie archiwum spowodowało błąd. Kod błędu: %code%.',
    'Please select a valid destination folder for %title%.' => 'Wybierz poprawne miejsce docelowe dla %title%.',
    'Save' => 'Zapisz',
    'Selected items...' => 'Zaznaczone obiekty...',
    'Show' => 'Pokaż',
    'Show Post' => 'Pokaż Post',
    'Size' => 'Rozmiar',
    'The archive could not be created.' => 'Nie można było utworzyć archiwum.',
    'The folder %filename% already exists. Contents have been overwritten.' => 'Katalog %filename% jest już utworzony. Zawartość została nadpisana.',
    'The folder with the id %id% does not exist.' => 'Katalog o ID %id% nie istnieje.',
    'This folder is empty.' => 'Katalog jest pusty.',
    'Unfortunately you have no permission to upload/edit files.' => 'Niestety nie masz uprawnień do przesyłania/edycji plików.',
    'Updated' => 'Zaktualizowane',
    'Upload' => 'Prześlij',
    'Upload files or create a subfolder with the buttons on the top.' => 'Prześlij pliku lub utwórz podkatalog za pomocą przycisków na górze.',
    'Upload files to the stream to fill this folder.' => 'Prześlij pliki na strumień aby wypełnić katalog zawartością.',
    'root' => 'root',
];
