<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> delete file' => '',
    'Add file(s)' => '',
    'Adds an file module to this space.' => '',
    'Adds files module to your profile.' => '',
    'Archive' => '',
    'Archive folder' => '',
    'Archive selected' => '',
    'Do you really want to delete this %number% item(s) wit all subcontent?' => '',
    'Enable Zip Support' => '',
    'File' => '',
    'Files Module Configuration' => '',
    'Folder' => '',
    'Folder options' => '',
    'Insufficient rights to execute this action.' => '',
    'Invalid parameter.' => '',
    'Opening archive failed with error code %code%.' => '',
    'Selected items...' => '',
    'This folder is empty.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Upload' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'Zip support is not enabled.' => '',
    ' The folder %filename% could not be saved.' => 'Nie można zapisać katalogu %filename%.',
    '%filename% has invalid extension and was skipped.' => '%filename% ma nieprawidłowe rozszerzenie i został pominięty.',
    '%title% was replaced by a newer version.' => '%title% zastąpiono nowszą wersją.',
    '/ (root)' => '/ (root)',
    '<strong>Create</strong> folder' => '<strong>Utwórz</strong> nowy folder',
    '<strong>Edit</strong> folder' => '<strong>Edytuj</strong> katalog',
    '<strong>Move</strong> files' => '<strong>Przenieś</strong> pliki',
    'A folder with this name already exists' => 'Katalog o takiej nazwie już istnieje',
    'Add directory' => 'Dodaj katalog',
    'All posted files' => 'Wszystkie opublikowane pliki',
    'Archive %filename% could not be extracted.' => 'Nie można rozpakować %filename%.',
    'Close' => 'Zamknij',
    'Could not save file %title%. ' => 'Nie można zapisać %title%.',
    'Creator' => 'Właściciel',
    'Delete' => 'Usuń',
    'Download' => 'Pobierz',
    'Download .zip' => 'Pobierz .zip',
    'Download zip' => 'Pobierz ZIP',
    'Edit' => 'Edycja',
    'Edit directory' => 'Edytuj katalog',
    'Files' => 'Pliki',
    'Move' => 'Przenieś',
    'Move file' => 'Przenieś plik',
    'Move folder' => 'Przenieś katalog',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => 'Przenoszenie do tego samego katalogu jest niemożliwe. Wybierz poprawny katalog nadrzędny dla %title%.',
    'Name' => 'Nazwa',
    'No valid items were selected to move.' => 'Nie zaznaczono poprawnych elementów do przeniesienia.',
    'Open' => 'Otwórz',
    'Please select a valid destination folder for %title%.' => 'Wybierz poprawne miejsce docelowe dla %title%.',
    'Save' => 'Zapisz',
    'Should not start or end with blank space.' => 'Bez białych znaków na początku i końcu.',
    'Show' => 'Pokaż',
    'Show Image' => 'Pokaż Obrazek',
    'Show Post' => 'Pokaż Post',
    'Size' => 'Rozmiar',
    'The archive could not be created.' => 'Nie można było utworzyć archiwum.',
    'The folder %filename% already exists. Contents have been overwritten.' => 'Katalog %filename% jest już utworzony. Zawartość została nadpisana.',
    'The folder with the id %id% does not exist.' => 'Katalog o ID %id% nie istnieje.',
    'Updated' => 'Zaktualizowane',
    'Upload .zip' => 'Prześlij .zip',
    'root' => 'root',
];
