<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> file' => '',
    '<strong>File</strong> download url' => '',
    '<strong>File</strong> url' => '',
    '<strong>Files</strong> module configuration' => '',
    '<strong>Folder</strong> url' => '',
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '',
    'A file with that name already exists in this folder.' => '',
    'A folder with this name already exists.' => '',
    'Adds files module to this space.' => '',
    'An error occurred while creating folder {folder}.' => '',
    'An error occurred while unpacking {filename}.' => '',
    'Cannot edit non existing file.' => '',
    'Could not find folder with id: %id%' => '',
    'Destination folder not found!' => '',
    'Disable archive (ZIP) support' => '',
    'Display Url' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Download ZIP' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Folder {name} can\'t be moved to itself!' => '',
    'Folder {name} given folder is not editable!' => '',
    'Import Zip' => '',
    'Likes/Comments' => '',
    'Make Private' => '',
    'Make Public' => '',
    'Moving to the same folder is not valid.' => '',
    'Moving to this folder is invalid.' => '',
    'Open file folder' => '',
    'Replace existing files' => '',
    'Root' => '',
    'Size: {size}' => '',
    'Some files could not be imported: ' => '',
    'Some files could not be moved: ' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This file is only visible for you and your friends.' => '',
    'This file is private.' => '',
    'This file is protected.' => '',
    'This file is public.' => '',
    'This folder is only visible for you and your friends.' => '',
    'This folder is private.' => '',
    'This folder is protected.' => '',
    'This folder is public.' => '',
    'Upload behaviour for existing file names' => '',
    'Use of file indexes for already existing files' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP selected' => '',
    'ZIP support is not enabled.' => '',
    '%filename% has invalid extension and was skipped.' => '%filename% ma nieprawidłowe rozszerzenie i został pominięty.',
    '/ (root)' => '/ (root)',
    '<strong>Confirm</strong> delete file' => '<strong>Potwierdź</strong> usunięcie pliku',
    '<strong>Create</strong> folder' => '<strong>Utwórz</strong> nowy folder',
    '<strong>Edit</strong> folder' => '<strong>Edytuj</strong> katalog',
    '<strong>Move</strong> files' => '<strong>Przenieś</strong> pliki',
    'Add directory' => 'Dodaj katalog',
    'Add file(s)' => 'Dodaj Plik(i)',
    'Adds files module to your profile.' => 'Dodaje moduł plików do twojego profilu',
    'Archive %filename% could not be extracted.' => 'Nie można rozpakować %filename%.',
    'Creator' => 'Właściciel',
    'Delete' => 'Usuń',
    'Download' => 'Pobierz',
    'Edit' => 'Edycja',
    'Edit directory' => 'Edytuj katalog',
    'File' => 'Plik',
    'Files' => 'Pliki',
    'Folder' => 'Katalog',
    'Move' => 'Przenieś',
    'Name' => 'Nazwa',
    'Open' => 'Otwórz',
    'Opening archive failed with error code %code%.' => 'Otwarcie archiwum spowodowało błąd. Kod błędu: %code%.',
    'Please select a valid destination folder for %title%.' => 'Wybierz poprawne miejsce docelowe dla %title%.',
    'Selected items...' => 'Zaznaczone obiekty...',
    'Show Post' => 'Pokaż Post',
    'Size' => 'Rozmiar',
    'This folder is empty.' => 'Katalog jest pusty.',
    'Unfortunately you have no permission to upload/edit files.' => 'Niestety nie masz uprawnień do przesyłania/edycji plików.',
    'Updated' => 'Zaktualizowane',
    'Upload files or create a subfolder with the buttons on the top.' => 'Prześlij pliku lub utwórz podkatalog za pomocą przycisków na górze.',
    'Upload files to the stream to fill this folder.' => 'Prześlij pliki na strumień aby wypełnić katalog zawartością.',
];
