<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%filename% has invalid extension and was skipped.' => '',
    '/ (root)' => '',
    '<strong>Create</strong> folder' => '',
    '<strong>File</strong> url' => '',
    '<strong>Files</strong> module configuration' => '',
    '<strong>Folder</strong> url' => '',
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '',
    'A file with that name already exists in this folder.' => '',
    'A folder with this name already exists.' => '',
    'Adds files module to this space.' => '',
    'Adds files module to your profile.' => '',
    'An error occurred while creating folder {folder}.' => '',
    'An error occurred while unpacking {filename}.' => '',
    'Archive %filename% could not be extracted.' => '',
    'Cannot edit non existing file.' => '',
    'Could not find folder with id: %id%' => '',
    'Destination folder not found!' => '',
    'Disable archive (ZIP) support' => '',
    'Edit directory' => '',
    'Folder' => '',
    'Folder should not start or end with blank space.' => '',
    'Folder {name} can\'t be moved to itself!' => '',
    'Folder {name} given folder is not editable!' => '',
    'Import Zip' => '',
    'Make Private' => '',
    'Make Public' => '',
    'Moving to this folder is invalid.' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Replace existing files' => '',
    'Root' => '',
    'Selected items...' => '',
    'Size: {size}' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This file is only visible for you and your friends.' => '',
    'This file is protected.' => '',
    'This folder is only visible for you and your friends.' => '',
    'This folder is protected.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Upload behaviour for existing file names' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'Use of file indexes for already existing files' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP selected' => '',
    'ZIP support is not enabled.' => '',
    '<strong>Confirm</strong> delete file' => 'Fájl <strong>törlésének</strong> jóváhagyása',
    '<strong>Edit</strong> file' => 'Fájl <strong>szerkesztése</strong>',
    '<strong>Edit</strong> folder' => 'Mappa <strong>szerkesztése</strong>',
    '<strong>File</strong> download url' => 'URL a fájl <strong>letöltéséhez</strong>',
    '<strong>Move</strong> files' => 'Fájlok <strong>mozgatása</strong>',
    'Add directory' => 'Új mappa',
    'Add file(s)' => 'Fájl(ok) feltöltése',
    'Creator' => 'Feltöltő',
    'Delete' => 'Törlés',
    'Display Url' => 'URL megjelenítése',
    'Do you really want to delete this {number} item(s) with all subcontent?' => 'Biztosan törölni akar {number} elemet az esetleges almappákkal együtt?',
    'Download' => 'Letöltés',
    'Download ZIP' => 'Letöltés ZIP fájlba',
    'Edit' => 'Szerkesztés',
    'File' => 'Fájl',
    'Files' => 'Fájlok',
    'Files from the stream' => 'Hírfolyamba feltöltött fájlok',
    'Likes/Comments' => 'Tetszik/hozzászólások',
    'Move' => 'Mozgatás',
    'Moving to the same folder is not valid.' => 'A fájl nem mozgatható a jelenlegi mappájába.',
    'Name' => 'Név',
    'Open' => 'Megnyitás',
    'Open file folder' => 'Fájl mappájának megnyitása',
    'Show Post' => 'Ugrás a bejegyzésre',
    'Size' => 'Méret',
    'Some files could not be imported: ' => 'Néhány fájl importálása nem sikerült.',
    'Some files could not be moved: ' => 'Néhány fájl mozgatása nem sikerült.',
    'This file is private.' => 'Ez a fájl privát.',
    'This file is public.' => 'Ez a fájl nyilvános.',
    'This folder is empty.' => 'Ez a mappa üres.',
    'This folder is private.' => 'Ez a mappa privát.',
    'This folder is public.' => 'Ez a mappa nyilvános.',
    'Updated' => 'Szerkesztve',
];
