<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> file' => '',
    'An internal error occurred. Could not find folder with id: %id%' => '',
    'An internal error occurred. Could not load default folder containing all posted files, database not properly initialized.' => '',
    'An internal error occurred. Could not load root folder, database not properly initialized.' => '',
    'Cannot edit non existing file.' => '',
    'Collapse' => '',
    'Created at:' => '',
    'Created by:' => '',
    'Edit the file description...' => '',
    'Edit the folder description...' => '',
    'Filesize:' => '',
    'Folder should not start or end with blank space.' => '',
    'Insufficient rights to execute this action.' => '',
    'Invalid parameter.' => '',
    'Last edited at:' => '',
    'Last edited by:' => '',
    'Likes/Comments' => '',
    'Move' => '',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => '',
    'Name' => '',
    'No valid items were selected to move.' => '',
    'Open' => '',
    'Open directory!' => '',
    'Open parent directory!' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Save' => '',
    'Schließen' => '',
    'Selected items...' => '',
    'Show Image' => '',
    'Show Post' => '',
    'Show all files' => '',
    'Show complete file preview' => '',
    'Show on Wall' => '',
    'Size' => '',
    'The archive could not be created.' => '',
    'The folder %filename% already exists. Contents have been overwritten.' => '',
    'The folder with the id %id% does not exist.' => '',
    'This folder is empty.' => '',
    'This folder is still empty.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Updated' => '',
    'Upload' => '',
    'Upload ZIP' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    'changed:' => '',
    'created:' => '',
    ' The folder %filename% could not be saved.' => 'Dosarul %filename% nu s-a putut salva.',
    '%filename% has invalid extension and was skipped.' => '%filename% are o extensie invalida si a fost sarit.',
    '%title% was replaced by a newer version.' => '%title% a fost inlocuit de o noua versiune.',
    '/ (root)' => '/ (sursa)',
    '<strong>Confirm</strong> delete file' => '<strong>Confirma</strong> stergerea fisierului',
    '<strong>Create</strong> folder' => '<strong>Creeaza</strong> dosar',
    '<strong>Edit</strong> folder' => '<strong>Editeaza</strong> dosarul',
    '<strong>Files</strong> module configuration' => 'Configurarea modulului de <strong>Fisiere</strong>',
    '<strong>Move</strong> files' => '<strong>Muta</strong> fisiere',
    'A folder with this name already exists.' => 'Un dosar cu acelasi nume exista deja.',
    'Add directory' => 'Adauga director',
    'Add file(s)' => 'Adauga fisier(e)',
    'Adds files module to this space.' => 'Adauga modulul de fisiere la acest spatiu.',
    'Adds files module to your profile.' => 'Adauga modulul de fisiere la profilul tau.',
    'Archive %filename% could not be extracted.' => 'Arhiva %filename% nu s-a putut extrage.',
    'Archive (zip) support is not enabled.' => 'Arhiva (zip) nu este activata.',
    'Close' => 'Inchide',
    'Could not save file %title%. ' => 'Nu am putut salva fisierul %title%.',
    'Creator' => 'Creator',
    'Delete' => 'Sterge',
    'Disable archive (ZIP) support' => 'Dezactiveaza suportul pentru arhive (ZIP)',
    'Do you really want to delete this %number% item(s) with all subcontent?' => 'Sigur doresti sa stergi aceste %number% elemente impreuna cu subcontinuturile sale?',
    'Download' => 'Descarca',
    'Download ZIP' => 'Descarca ZIP',
    'Edit' => 'Editeaza',
    'Edit directory' => 'Editeaza directorul',
    'File' => 'Fisier',
    'Files' => 'Fisiere',
    'Folder' => 'Dosar',
    'Folder options' => 'Optiuni dosar',
];
