<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> file' => '',
    '<strong>File</strong> download url' => '',
    '<strong>File</strong> url' => '',
    '<strong>Folder</strong> url' => '',
    '<strong>Note:</strong> The replacement behaviour is currently not supported for zip imports.' => '',
    'A file with that name already exists in this folder.' => '',
    'An error occurred while creating folder {folder}.' => '',
    'An error occurred while unpacking {filename}.' => '',
    'Cannot edit non existing file.' => '',
    'Could not find folder with id: %id%' => '',
    'Destination folder not found!' => '',
    'Display Url' => '',
    'Do you really want to delete this {number} item(s) with all subcontent?' => '',
    'Files from the stream' => '',
    'Folder should not start or end with blank space.' => '',
    'Folder {name} can\'t be moved to itself!' => '',
    'Folder {name} given folder is not editable!' => '',
    'Import Zip' => '',
    'Likes/Comments' => '',
    'Make Private' => '',
    'Make Public' => '',
    'Move' => '',
    'Moving to the same folder is not valid.' => '',
    'Moving to this folder is invalid.' => '',
    'Name' => '',
    'Open' => '',
    'Open file folder' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Replace existing files' => '',
    'Root' => '',
    'Selected items...' => '',
    'Show Post' => '',
    'Size' => '',
    'Size: {size}' => '',
    'Some files could not be imported: ' => '',
    'Some files could not be moved: ' => '',
    'The root folder is the entry point that contains all available files.' => '',
    'This file is only visible for you and your friends.' => '',
    'This file is private.' => '',
    'This file is protected.' => '',
    'This file is public.' => '',
    'This folder is empty.' => '',
    'This folder is only visible for you and your friends.' => '',
    'This folder is private.' => '',
    'This folder is protected.' => '',
    'This folder is public.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Updated' => '',
    'Upload behaviour for existing file names' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'Use of file indexes for already existing files' => '',
    'You can find all files that have been posted to this stream here.' => '',
    'ZIP selected' => '',
    'ZIP support is not enabled.' => '',
    '%filename% has invalid extension and was skipped.' => '%filename% are o extensie invalida si a fost sarit.',
    '/ (root)' => '/ (sursa)',
    '<strong>Confirm</strong> delete file' => '<strong>Confirma</strong> stergerea fisierului',
    '<strong>Create</strong> folder' => '<strong>Creeaza</strong> dosar',
    '<strong>Edit</strong> folder' => '<strong>Editeaza</strong> dosarul',
    '<strong>Files</strong> module configuration' => 'Configurarea modulului de <strong>Fisiere</strong>',
    '<strong>Move</strong> files' => '<strong>Muta</strong> fisiere',
    'A folder with this name already exists.' => 'Un dosar cu acelasi nume exista deja.',
    'Add directory' => 'Adauga director',
    'Add file(s)' => 'Adauga fisier(e)',
    'Adds files module to this space.' => 'Adauga modulul de fisiere la acest spatiu.',
    'Adds files module to your profile.' => 'Adauga modulul de fisiere la profilul tau.',
    'Archive %filename% could not be extracted.' => 'Arhiva %filename% nu s-a putut extrage.',
    'Creator' => 'Creator',
    'Delete' => 'Sterge',
    'Disable archive (ZIP) support' => 'Dezactiveaza suportul pentru arhive (ZIP)',
    'Download' => 'Descarca',
    'Download ZIP' => 'Descarca ZIP',
    'Edit' => 'Editeaza',
    'Edit directory' => 'Editeaza directorul',
    'File' => 'Fisier',
    'Files' => 'Fisiere',
    'Folder' => 'Dosar',
];
