<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' The folder %filename% could not be saved.' => '',
    '%filename% has invalid extension and was skipped.' => '',
    '%title% was replaced by a newer version.' => '',
    '/ (root)' => '',
    '<strong>Confirm</strong> delete file' => '',
    '<strong>Create</strong> folder' => '',
    '<strong>Edit</strong> folder' => '',
    '<strong>Files</strong> module configuration' => '',
    '<strong>Move</strong> files' => '',
    'A folder with this name already exists.' => '',
    'Add directory' => '',
    'Add file(s)' => '',
    'Adds files module to this space.' => '',
    'Adds files module to your profile.' => '',
    'Archive %filename% could not be extracted.' => '',
    'Archive (zip) support is not enabled.' => '',
    'Close' => '',
    'Could not save file %title%. ' => '',
    'Creator' => '',
    'Delete' => '',
    'Disable archive (ZIP) support' => '',
    'Do you really want to delete this %number% item(s) with all subcontent?' => '',
    'Download' => '',
    'Download ZIP' => '',
    'Edit' => '',
    'Edit directory' => '',
    'File' => '',
    'Files' => '',
    'Files from the stream' => '',
    'Folder' => '',
    'Folder options' => '',
    'Folder should not start or end with blank space.' => '',
    'Insufficient rights to execute this action.' => '',
    'Invalid parameter.' => '',
    'Move' => '',
    'Moving to the same folder is not valid. Choose a valid parent folder for %title%.' => '',
    'Name' => '',
    'No valid items were selected to move.' => '',
    'Open' => '',
    'Opening archive failed with error code %code%.' => '',
    'Please select a valid destination folder for %title%.' => '',
    'Save' => '',
    'Selected items...' => '',
    'Show' => '',
    'Show Post' => '',
    'Size' => '',
    'The archive could not be created.' => '',
    'The folder %filename% already exists. Contents have been overwritten.' => '',
    'The folder with the id %id% does not exist.' => '',
    'This folder is empty.' => '',
    'Unfortunately you have no permission to upload/edit files.' => '',
    'Updated' => '',
    'Upload' => '',
    'Upload ZIP' => '',
    'Upload files or create a subfolder with the buttons on the top.' => '',
    'Upload files to the stream to fill this folder.' => '',
    'ZIP all' => '',
    'ZIP selected' => '',
    'changed:' => '',
    'created:' => '',
    'root' => '',
];
